workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore
      vars:
        BUNDLE_ID: "com.munja.app"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true