workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      groups:
        - appstore
      vars:
        BUNDLE_ID: "com.munja.app"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Show Flutter version info
        script: |
          grep version pubspec.yaml

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --platform IOS --type IOS_APP_STORE --create

      - name: Set up keychain and profiles
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build unsigned Flutter iOS app
        script: |
          flutter build ios --release --no-codesign --build-name=1.0.2 --build-number=5

      - name: Build signed IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true