// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Ik1xgUJp9GEs5TWxszeuymmfT1JWswU',
    appId: '1:953344223447:web:1fb314c268b8ddf9e0a892',
    messagingSenderId: '953344223447',
    projectId: 'munja-3d36e',
    authDomain: 'munja-3d36e.firebaseapp.com',
    storageBucket: 'munja-3d36e.firebasestorage.app',
    measurementId: 'G-91FYKJ015G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6M7fRdiraseDo-IUQgdDv_NmLUat2FDI',
    appId: '1:953344223447:android:3ac794c50a4edd27e0a892',
    messagingSenderId: '953344223447',
    projectId: 'munja-3d36e',
    storageBucket: 'munja-3d36e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFbpvV3oNEEgQOcJe_5UDWgEA5HfN3nhE',
    appId: '1:953344223447:ios:f44adadac58e6ee4e0a892',
    messagingSenderId: '953344223447',
    projectId: 'munja-3d36e',
    storageBucket: 'munja-3d36e.firebasestorage.app',
    iosClientId:
        '953344223447-dj4b1duniki1vjlgbddl0jq8hnfu2h9p.apps.googleusercontent.com',
    iosBundleId: 'com.munja.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFbpvV3oNEEgQOcJe_5UDWgEA5HfN3nhE',
    appId: '1:953344223447:ios:b37718d26b98e3b7e0a892',
    messagingSenderId: '953344223447',
    projectId: 'munja-3d36e',
    storageBucket: 'munja-3d36e.firebasestorage.app',
    iosClientId:
        '953344223447-3kjgnjnb3kd3icsjpoloom9bprtbpog9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartProductsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Ik1xgUJp9GEs5TWxszeuymmfT1JWswU',
    appId: '1:953344223447:web:819a6a312f7260f0e0a892',
    messagingSenderId: '953344223447',
    projectId: 'munja-3d36e',
    authDomain: 'munja-3d36e.firebaseapp.com',
    storageBucket: 'munja-3d36e.firebasestorage.app',
    measurementId: 'G-VRGYRB4Z3T',
  );
}
