const Map<String, String> bs = {
  'appTitle': 'Munja',

  // Login / authentication
  'authGenericError': 'Nešto je pošlo po zlu. Pokušaj ponovo.',
  'googleLoginFailed': 'Google prijava nije mogla biti završena.',
  'appleLoginFailed': 'Apple prijava nije mogla biti završena.',
  'enterEmailFirst': 'Prvo unesi svoju e-mail adresu.',
  'resetPasswordSent': 'Poslali smo ti link za promjenu lozinke.',
  'resetPasswordFailed': 'Promjena lozinke nije mogla biti završena.',
  'createMunjaAccount': 'Kreiraj svoj Munja račun',
  'welcomeBack': 'Dobrodošao nazad',
  'createAccountSubtitle':
      'Napravi svoj digitalni bicikl, poveži proizvode i sačuvaj vožnje na jednom mjestu.',
  'loginSubtitle': 'Nastavi do svog bicikla, vožnji i digitalnog svijeta.',
  'yourName': 'Tvoje ime',
  'email': 'E-mail',
  'emailHint': 'ime@email.com',
  'password': 'Lozinka',
  'passwordHint': 'Najmanje 6 znakova',
  'forgotPassword': 'Zaboravljena lozinka?',
  'createAccount': 'Kreiraj račun',
  'signIn': 'Prijavi se',
  'continueApple': 'Nastavi s Appleom',
  'continueGoogle': 'Nastavi s Googleom',
  'alreadyAccount': 'Već imaš račun?',
  'noAccount': 'Nemaš račun?',
  'or': 'ILI',
  'digitalCyclingPlatform': 'DIGITALNA BICIKLISTIČKA PLATFORMA',
  'rideConnectEvolve': 'VOZI • POVEŽI • NAPREDUJ',
  'language': 'Jezik',

  'welcome': 'Dobrodošli',
  'welcomeToMunja': 'Dobrodošli u Munju',
  'howToUseApp': 'Kako koristiti aplikaciju',
  'howToUseAppBody':
      '1. Koristi Auto Ride za automatsko praćenje.\n2. Koristi Ciljeve za ciljeve i navike.\n3. Koristi Opremu ako imaš Smart Brake Light.\n4. Otvori svoj digitalni bicikl na početnoj strani.',

  'chooseAvatarMode': 'Odaberi avatar način',
  'avatarModeSubtitle': 'Učini aplikaciju ličnijom prije početka.',
  'setupBeforeStart': 'Podešavanje prije početka',
  'setupBeforeStartSubtitle': 'Dodaj svoje podatke prije ulaska u aplikaciju.',
  'name': 'Ime',
  'age': 'Godine',
  'city': 'Grad',
  'startApp': 'Pokreni aplikaciju',
  'back': 'Nazad',
  'next': 'Dalje',
  'appMode': 'Način aplikacije',

  'home': 'Početna',
  'ride': 'Vožnja',
  'challenge': 'Ciljevi',
  'products': 'Oprema',
  'goals': 'Ciljevi',
  'gear': 'Oprema',
  'profile': 'Profil',
  'routes': 'Rute',
  'coach': 'Trener',
  'analytics': 'Analitika',

  'ready': 'Spremno',
  'live': 'Uživo',
  'route': 'Ruta',
  'time': 'Vrijeme',
  'level': 'Nivo',
  'distance': 'Udaljenost',
  'speed': 'Brzina',
  'duration': 'Trajanje',
  'avg': 'Prosjek',
  'avgSpeed': 'Prosječna brzina',
  'calories': 'Kalorije',
  'routePoints': 'Tačke rute',
  'total': 'Ukupno',
  'last': 'Zadnje',
  'lastRide': 'Zadnja vožnja',
  'rides': 'Vožnje',
  'thisWeek': 'Ove sedmice',
  'weeklyGoal': 'Sedmični cilj',

  'digital_twin_ready': 'Digitalni blizanac spreman',
  'gps': 'GPS',
  'bluetooth': 'Bluetooth',
  'battery': 'Baterija',
  'active': 'Aktivno',
  'inactive': 'Neaktivno',
  'hold_to_start': 'Drži za start',
  'hold_to_stop': 'Drži za stop',
  'smart_brake_light_connected': 'Smart Lighting Brake povezan',
  'tap_bike_to_manage_gear': 'Dodirni bicikl za upravljanje opremom',

  'goodMorning': 'Dobro jutro',
  'goodAfternoon': 'Dobar dan',
  'goodEvening': 'Dobro veče',
  'homeHeadline': 'Tvoj bicikl živi digitalno',
  'startAutoRideBody':
      'Drži kristal za početak vožnje i otvori svoj digitalni bicikl.',
  'streak': 'Niz',
  'days': 'dana',

  'greenerTransport': 'Zeleniji transport',
  'greenImpact': 'Tvoj zeleni uticaj',
  'greenImpactSubtitle':
      'Kada odabereš bicikl umjesto auta, pomažeš smanjiti CO₂ i nepotrebne vožnje autom.',
  'co2Saved': 'Ušteđeni CO₂',
  'carKmAvoided': 'Izbjegnuti auto-km',
  'greenImpactPositive':
      'Već si napravio razliku ove sedmice. Svaka vožnja pomaže smanjiti saobraćaj, potrošnju goriva i CO₂.',
  'greenImpactStart':
      'Pokreni prvu vožnju i vidi koliko CO₂ možeš uštedjeti birajući bicikl umjesto auta.',
  'monthlyOverview': 'Mjesečni pregled',
  'monthlyOverviewSubtitle':
      'Pogledaj napredak iz mjeseca u mjesec kroz udaljenost i zeleniji transport.',
  'totalSixMonths': 'Ukupno 6 mjeseci',
  'totalCo2Saved': 'Ukupno ušteđeni CO₂',

  'hardware': 'Hardware',
  'hardwareNearby': 'Tvoj Smart Brake Light je u blizini.',
  'noHardwareFound':
      'Trenutno nema pronađenog hardware-a. Aplikacija i dalje može raditi samostalno.',
  'allProducts': 'Sva oprema',
  'smartBrakeLight': 'Smart Brake Light',
  'openStatusSensitivityConnection':
      'Otvori status, osjetljivost i informacije o vezi',
  'scanSaveManageDevices': 'Skeniraj, sačuvaj i upravljaj Munja uređajima',
  'locationPermissionsMissing': 'Nedostaju dozvole za lokaciju',
  'bluetoothPermissionMissing': 'Nedostaje Bluetooth ili dozvola za lokaciju',
  'tryingToConnect': 'Pokušavam povezivanje…',
  'noSavedDeviceYet': 'Još nema sačuvanog uređaja',
  'connected': 'Povezano',
  'disconnected': 'Prekinuto',
  'couldNotConnect': 'Nije moguće povezati',
  'connecting': 'POVEZIVANJE…',
  'notConnected': 'NIJE POVEZANO',
  'connectNow': 'Poveži sada',
  'brakeLightSensitivity': 'Osjetljivost kočionog svjetla',
  'sensitivityHint': 'Nisko = brže reaguje · Visoko = zahtijeva jače kočenje',
  'hardwareFound': 'Hardware pronađen',
  'softwareOnly': 'Samo software',

  'autoRide': 'Auto Ride',
  'automaticTracking': 'Automatsko praćenje',
  'automaticTrackingSubtitle':
      'Koristi dva prsta za zumiranje na mapi, a vožnja se automatski zaustavlja nakon 30 sekundi ispod granice zaustavljanja.',
  'monitoring': 'Praćenje',
  'notStarted': 'NIJE POKRENUTO',
  'stopMonitoring': 'Zaustavi praćenje',
  'startAutoMode': 'Pokreni auto način',
  'stopTracking': 'Zaustavi tracking',
  'openAutoRide': 'Otvori Auto Ride',

  'map': 'Mapa',
  'mapSubtitle':
      'Koristi dva prsta za zumiranje. Možeš koristiti i dugmad ili se vratiti na trenutnu lokaciju.',
  'myLocation': 'Moja lokacija',
  'yourPosition': 'Tvoja pozicija',
  'recentRides': 'Nedavne vožnje',
  'recentRidesSubtitle':
      'Sačuvane vožnje zadržavaju svoju rutu. Dodirni vožnju da je vidiš na mapi.',
  'noRidesSavedYet': 'Još nema sačuvanih vožnji.',
  'rideRoute': 'Ruta vožnje',
  'start': 'Start',
  'finish': 'Cilj',

  'bikeChallenge': 'Biciklistički ciljevi',
  'yourChallenge': 'Tvoj cilj',
  'yourChallengeSubtitle': 'Postavi rok i napravi od biciklizma stalnu naviku.',
  'setChallengeDate': 'Postavi datum za svoj cilj.',
  'deadlinePassed': 'Rok je prošao — postavi novi 💪',
  'itIsToday': 'To je danas! 🚴',
  'daysLeft': 'dana preostalo',
  'setDate': 'Postavi datum',
  'changeDate': 'Promijeni datum',
  'startChallenge': 'Pokreni cilj',
  'planAndGoal': 'Plan i cilj',
  'planAndGoalSubtitle': 'Odaberi kada obično voziš i prilagodi sedmični cilj.',
  'bikeToWork': 'Biciklom na posao',
  'afterWork': 'Poslije posla',
  'weekend': 'Vikend',
  'morning': 'Jutro',
  'yourPlan': 'Tvoj plan',
  'openGuide': 'Otvori vodič',
  'challengeGuide': 'Vodič za ciljeve',
  'dailySteps': 'Dnevni koraci',
  'mindset': 'Mentalitet',
  'startSetGoal': 'Počni — postavi cilj',
  'writeDownDate': 'Zapiši datum.',
  'chooseRideTime': 'Odaberi kada želiš voziti tokom sedmice.',
  'makeStartEasy': 'Učini početak što lakšim.',
  'findRoutineTime': 'Nađi 10–20 minuta u svojoj rutini.',
  'takeShortRide': 'Reci sebi: Danas ću samo kratko provozati.',
  'repeatHabit': 'Ponavljaj dok ne postane navika.',
  'focusProgress': 'Fokusiraj se na napredak, ne na savršenstvo.',
  'holdSmallWins': 'Drži se malih pobjeda.',
  'importantAction': 'Najvažnije je krenuti.',

  'profileSettings': 'Avatar i postavke',
  'riderIdentity': 'Tvoj biciklistički identitet',
  'riderIdentitySubtitle': 'Odaberi avatar način i ažuriraj svoje podatke.',
  'saveAvatarProfile': 'Sačuvaj avatar i profil',
  'profileSaved': 'Avatar i profil su sačuvani',

  'myProducts': 'Moja oprema',
  'nearby': 'U blizini',
  'scanProductsSubtitle': 'Skeniraj Munja opremu oko sebe.',
  'noProductsNearby': 'Nema opreme u blizini.',
  'savedProducts': 'Sačuvana oprema',
  'savedProductsSubtitle': 'Uređaji koje si ranije sačuvao.',
  'noSavedProducts': 'Još nema sačuvane opreme.',
  'saved': 'Sačuvano',
  'save': 'Sačuvaj',
  'add': 'Dodaj',

  'classicRider': 'Klasični vozač',
  'speedMode': 'Brzi način',
  'ecoMode': 'Eko način',
  'challengeMode': 'Ciljni način',
  'nightRide': 'Noćna vožnja',
  'safeRider': 'Siguran vozač',

  'smartRoutePlanner': 'Pametni planer ruta',
  'smartRouteAi': 'Smart Route AI',
  'searchAddress': 'Pretraži adresu...',
  'destination': 'Odredište',
  'enterWhereYouWantToRide': 'Unesi gdje želiš voziti.',
  'generateRoute': 'Generiši rutu',
  'generating': 'Generišem...',
  'searching': 'Pretražujem...',
  'routePreview': 'Pregled rute',
  'addressSearchNow':
      'Pretraga adrese sada. Pravi road-routing API dolazi kasnije.',
  'whyThisRoute': 'Zašto ova ruta?',
  'munjaScoresRoute': 'Munja je ocjenjuje na osnovu tvog stila.',
  'safety': 'Sigurnost',
  'scenic': 'Lijepa ruta',
  'fitness': 'Fitness',
  'useThisRoute': 'Koristi ovu rutu',
  'generateNewSuggestions': 'Generiši nove prijedloge',
  'routeGenerated': 'Ruta generisana',
  'addressNotFound': 'Adresa nije pronađena.',
  'enterAddressFirst': 'Prvo unesi adresu.',
  'couldNotFindAddress': 'Nije moguće pronaći tu adresu.',
  'selectedAndSaved': 'odabrana i sačuvana.',

  'aiRideCoach': 'AI trener vožnje',
  'personalRideIntelligence':
      'Lična inteligencija vožnje, oporavak i savjeti za tempo.',
  'readiness': 'Spremnost',
  'fatigue': 'Umor',
  'consistency': 'Dosljednost',
  'todayPlan': 'Današnji plan',
  'recommendedRecentHistory': 'Preporučeno na osnovu nedavne historije vožnji.',
  'rideType': 'Tip vožnje',
  'coachIntelligence': 'Coach inteligencija',
  'whatMunjaNotices': 'Šta Munja primjećuje o tvojoj vožnji.',
  'adaptiveRecommendation': 'Prilagodljiva preporuka',
  'safetyLayer': 'Sigurnosni sloj',
  'performanceTrend': 'Trend performansi',
  'coachTips': 'Savjeti trenera',
  'smallActionsBetterRide': 'Male radnje za bolju vožnju.',
  'useRecommendation': 'Koristi preporuku',
  'coachRecommendationActivated': 'Preporuka trenera je aktivirana.',

  'monthlyProgress': 'Mjesečni napredak',
  'lastSixMonthsRiding': 'Zadnjih 6 mjeseci vožnje.',
  'consistencyCreatesResults': 'Dosljednost stvara rezultate.',
  'latestSavedTrips': 'Tvoje zadnje sačuvane vožnje.',
  'longest': 'Najduža',
  'achievements': 'Postignuća',
  'progressUnlocked': 'Napredak otključan iz ove vožnje.',
  'yourRidePathWasSaved': 'Tvoja ruta vožnje je sačuvana.',

  'openMap': 'Otvori mapu',
  'stop': 'Stop',
  'aiCoachActivated': 'AI trener aktiviran',
  'savedToMyProducts': 'sačuvano u Moju opremu',

  // Bike Customize
  'customize': 'Prilagodi',
  'skins': 'Skins',
  'frame': 'Frame',
  'livePreview': 'Live preview',
  'showroom': 'Showroom',
  'dragToRotateStageSync': 'Povuci za rotaciju · scena sinhronizovana',
  'frameTrail': 'Trail',
  'frameEnduro': 'Enduro',
  'frameRace': 'Race',
  'frameUrban': 'Urban',
  'colorMidnight': 'Midnight',
  'colorDeepBlack': 'Duboka crna',
  'colorMunjaMint': 'Munja Mint',
  'colorSignature': 'Prepoznatljiva',
  'colorArctic': 'Arctic',
  'colorCleanWhite': 'Čista bijela',
  'colorVelocity': 'Velocity',
  'colorElectricBlue': 'Električno plava',
  'colorPulse': 'Pulse',
  'colorPerformanceRed': 'Sportska crvena',
  'colorForest': 'Forest',
  'colorNatureGreen': 'Prirodno zelena',
  'skinStandard': 'Standard',
  'skinStandardSubtitle': 'Besplatne boje pod Okvir',
  'skinBrushedMetal': 'Brushed Metal',
  'skinPremiumMetal': 'Premium metal',
  'skinCarbonFibre': 'Carbon Fibre',
  'skinPremiumCarbon': 'Premium karbon',
  'skinGold': 'Gold',
  'skinPremiumFinish': 'Premium završna obrada',
  'skinIceSilver': 'Ice Silver',
  'skinColdMetallic': 'Hladni metalik',
  'skinLavaRed': 'Lava Red',
  'skinPerformanceFinish': 'Sportska završna obrada',
  'skinMattBlack': 'Matt Black',
  'skinStealthFinish': 'Stealth završna obrada',
  'skinNeonGreen': 'Neon Green',
  'skinElectricFinish': 'Električna završna obrada',
  'skinTitanium': 'Titanium',
  'skinEliteMetal': 'Elite metal',
  'owned': 'U vlasništvu',
  'pro': 'Pro',
  'locked': 'Zaključano',
  'munjaCrystals': 'Munja Crystals',
  'munjaPro': 'Munja Pro',
  'proExclusive': 'Samo za Pro',
  'crystalSkinDescription':
      'Ovaj skin se može otključati pomoću Munja Crystals. Kupovina će biti povezana u sljedećem velikom koraku.',
  'proSkinDescription':
      'Ovaj skin će biti dio Munja Pro. Pretplata će biti povezana kasnije.',
  'challengeReward': 'Nagrada za challenge',
  'rewardSkinDescription':
      'Ovaj skin se otključava kroz challenge ili achievement.',
  'gotIt': 'Razumijem',
  'comingNext': 'Dolazi sljedeće',
  'freeFrameColorActive':
      'Besplatna boja okvira je aktivna. Premium skin je isključen.',
  'frameColorSyncFailed':
      'Boju okvira nije moguće sinhronizovati. Pokušaj ponovo.',
  'frameChangeFailed': 'Okvir nije moguće promijeniti. Pokušaj ponovo.',
  'livePremiumPreview': 'Premium pregled uživo',
  'materialPending': 'materijal se priprema',
  'activeAndSynced': 'Aktivno i sinhronizovano',
  'skinActivationFailed': 'Skin nije moguće aktivirati. Pokušaj ponovo.',
  'skinsSectionSubtitle':
      'Premium materijali se prikazuju direktno na tvom 3D biciklu · besplatne boje su pod Okvir.',
  'livePremiumPreviews': 'Premium pregledi uživo',
  'skinStoreComingSoonMessage':
      'Skin Store katalog je spreman. Kupovina i otključavanje biće povezani u sljedećem koraku.',
  'munjaSkinStore': 'Munja Skin Store',
  'premiumProRewardSkins': 'Premium, Pro i reward skinovi',
  'equipped': 'Aktivirano',
  'proOnly': 'Samo Pro',
  'frameSectionSubtitle':
      'Odaberi geometriju i završnu obradu bez napuštanja showrooma.',
  'frameFinish': 'Završna obrada',
  'comingSoon': 'Uskoro',

  // Ride Setup / Route Planner
  'rideSetupSearchDestination': 'Pretraži odredište',
  'rideSetupCreateRoundTrip': 'Napravi kružnu vožnju',
  'rideSetupGetRouteSuggestions': 'Prikaži prijedloge ruta',
  'rideSetupStartFreeRide': 'Pokreni slobodnu vožnju',
  'rideSetupUseDestination': 'Koristi odredište',
  'rideSetupCreateRoundTripButton': 'Napravi kružnu vožnju',
  'rideSetupShowSuggestions': 'Prikaži prijedloge ruta',
  'rideSetupUseSelectedSuggestion': 'Koristi odabrani prijedlog',
  'rideSetupAddressSuggestionsUnavailable':
      'Prijedlozi adresa trenutno nisu dostupni.',
  'rideSetupGooglePlacesLocalFallback':
      'Google Places nije dostupan – prikazujem lokalne prijedloge.',
  'rideSetupShowingLocalSuggestions': 'Prikazujem lokalne prijedloge.',
  'rideSetupGpsUnavailable':
      'Munja nije mogla pronaći tvoju GPS lokaciju. Provjeri dozvolu za lokaciju i pokušaj ponovo.',
  'rideSetupNoGoodSuggestions':
      'Munja nije pronašla odgovarajuće rute u području.',
  'rideSetupChooseBestRoute': 'Odaberi rutu koja ti najbolje odgovara.',
  'rideSetupSuggestionsLoadFailed': 'Prijedloge ruta nije moguće učitati.',
  'rideSetupSuggestionsLoadFailedRetry':
      'Prijedloge ruta nije moguće učitati. Pokušaj ponovo.',
  'rideSetupChooseSuggestionFirst': 'Prvo odaberi prijedlog rute.',
  'rideSetupEnterAndChooseDestination': 'Unesi i odaberi odredište.',
  'rideSetupChooseAddressFromSuggestions': 'Odaberi adresu iz prijedloga.',
  'rideSetupTitle': 'Vožnja',
  'rideSetupHowRide': 'Kako želiš voziti?',
  'rideSetupChooseOneOption':
      'Odaberi jednu opciju. Munja prikazuje samo izbore koji su ti potrebni.',
  'rideSetupHowFar': 'Koliko daleko?',
  'rideSetupChooseApproxDistance': 'Odaberi približnu dužinu vožnje.',
  'rideSetupHowRouteFeel': 'Kakav osjećaj želiš na ruti?',
  'rideSetupRouteStyleSubtitle': 'Munja prilagođava rutu tvom stilu.',
  'rideSetupFindingSuggestions': 'Tražim prijedloge...',
  'rideSetupPreparing': 'Pripremam...',
  'rideSetupProPlannerActive': 'MUNJA PRO · Napredni planer ruta aktivan',
  'rideSetupProRequired': 'Ova vrsta rute zahtijeva MUNJA PRO',
  'rideSetupIntroTitle': 'Kako želiš voziti danas?',
  'rideSetupIntroSubtitle':
      'Odaberi vrstu vožnje. Ostale opcije se prikazuju tek kada su potrebne.',
  'rideSetupDestination': 'Odredište',
  'rideSetupDestinationSubtitle': 'Odaberi gdje želiš ići',
  'rideSetupRoundTrip': 'Kružna vožnja',
  'rideSetupRoundTripSubtitle': 'Kreni i vrati se na isto mjesto',
  'rideSetupMunjaSuggestions': 'Munja prijedlozi',
  'rideSetupMunjaSuggestionsSubtitle': 'Neka Munja pronađe vožnju',
  'rideSetupFreeRide': 'Slobodna vožnja',
  'rideSetupFreeRideSubtitle': 'Bez plana. Samo vozi.',
  'rideSetupChange': 'PROMIJENI',
  'rideSetupWhereTo': 'Gdje želiš ići?',
  'rideSetupSearchAddressOrDestination': 'Pretraži adresu ili odredište.',
  'rideSetupFreeHeroTitle': 'Bez rute. Samo vozi.',
  'rideSetupFreeHeroBody':
      'Munja i dalje bilježi tvoju vožnju, udaljenost i vrijeme.',
  'rideSetupChooseRideTypeContinue': 'Odaberi vrstu vožnje za nastavak',
  'rideSetupWheelReadyFree': 'Točak je spreman za slobodnu vožnju',
  'rideSetupWheelReadyPlanning': 'Točak ostaje spreman dok planiraš',
  'rideSetupSearchAddress': 'Pretraži adresu',
  'rideSetupBackToStart': 'Povratak na start',
  'rideSetupSuggestions': 'Prijedlozi',
  'rideSetupMunjaRecommends': 'Munja preporučuje',
  'rideSetupNoPlannedRoute': 'Nema planirane rute',
  'rideSetupRequiresPro': 'Zahtijeva Munja Pro',
  'rideSetupAddressHint': 'Unesi adresu ili odredište',
  'rideSetupClear': 'Obriši',
  'rideSetupLocalTestMode':
      'Test način: lokalni prijedlozi adresa. Dodaj GOOGLE_MAPS_API_KEY za Google prijedloge.',
  'rideSetupNoAddresses': 'Nema pronađenih adresa.',
  'rideSetupNoLocalAddresses': 'Nema pronađenih lokalnih test adresa.',
  'rideSetupChooseDestination': 'Odaberi odredište',
  'rideSetupEnterAddressRoute': 'Unesi adresu kako bi pronašao rutu.',
  'rideSetupAutomaticRoundTrip': 'Automatska kružna vožnja',
  'rideSetupRoundTripInfo': 'Munja čuva odabranu udaljenost i vrstu rute.',
  'rideSetupSuggestionsInfo':
      'Munja pronalazi više biciklističkih ruta oko tebe i usklađuje ih sa željenom udaljenošću.',
  'rideSetupFreeRideInfo': 'Pokreni praćenje vožnje bez fiksnog odredišta.',
  'rideSetupAround': 'Oko',
  'rideSetupFindNewSuggestions': 'Pronađi nove prijedloge',
  'rideSetupAnalyzingRoads': 'Munja analizira biciklističke rute oko tebe...',
  'rideSetupRoute': 'Ruta',
  'rideSetupVeryCloseDistance': 'Vrlo blizu željene udaljenosti',
  'rideSetupKmFromGoal': 'km od tvog cilja',
  'rideSetupBikeRoad': 'Cestovni',
  'rideSetupBikeFamily': 'Porodično',
  'rideSetupBikeNature': 'Priroda',
  'rideSetupBikeQuiet': 'Mirno',
  'rideSetupBikeQuietRoads': 'Mirne ceste',
  'rideSetupSelectedRide': 'Tvoja odabrana vožnja',

  // Ride Summary + Auto Ride
  'rideSummaryAiAnalysis': 'AI analiza vožnje',
  'rideSummaryAiProSubtitle':
      'Personalizovana Pro analiza na osnovu ove vožnje i tvoje historije.',
  'rideSummaryAiFreeSubtitle':
      'Jednostavan pregled vožnje. MUNJA PRO dodaje ličnu historiju i dublje preporuke.',
  'rideSummaryAnalyzing': 'Analiziram tvoju vožnju...',
  'rideSummaryAnalysisUnavailable': 'Analiza vožnje trenutno nije dostupna.',
  'rideSummaryProAnalysis': 'MUNJA PRO ANALIZA',
  'rideSummaryRideRecap': 'MUNJA PREGLED VOŽNJE',
  'rideSummaryConsistency': 'DOSLJEDNOST',
  'rideSummaryTrend': 'TREND',
  'rideSummaryFaster': 'BRŽE',
  'rideSummaryLonger': 'DUŽE',
  'rideSummarySteady': 'STABILNO',
  'rideSummaryHeader': 'MUNJA PREGLED',
  'rideRewards': 'NAGRADE ZA VOŽNJU',
  'loadingEarnedRewards': 'Učitavam osvojene nagrade...',
  'noCrystalRewardRide': 'Ova vožnja nije donijela Crystal nagradu.',
  'rideCompletedReward': 'Vožnja završena',
  'firstRideBonus': 'Bonus za prvu vožnju',
  'totalEarned': 'UKUPNO OSVOJENO',
  'crystalRewardsLoadFailed': 'Crystal nagrade nije moguće učitati.',
  'retry': 'POKUŠAJ PONOVO',
  'speedUnitShort': 'km/h',
  'autoRideArrivedSaved': 'Stigao si. Vožnja će se završiti i sačuvati.',
  'free': 'BESPLATNO',
  'autoRideLoopStarted': 'Kružna vožnja je počela · prati rutu',
  'autoRideArrived': 'Stigao si',
  'autoRideConfirmingArrival': 'Potvrđujem dolazak...',
  'autoRideRecalculating': 'Ponovo izračunavam rutu...',
  'autoRideCheckingRoute': 'Provjeravam rutu...',
  'autoRideNewRouteReady': 'Nova ruta je spremna',
  'autoRideCouldNotRecalculate': 'Nije moguće ponovo izračunati',
  'autoRideChooseDestinationHome': 'Odaberi odredište na početnoj stranici',
  'autoRideRouteActive': 'RUTA AKTIVNA',
  'autoRideThere': 'STIGAO',
  'autoRideWait': 'ČEKAJ',
  'autoRideOffRoute': 'VAN RUTE',
  'autoRideUpdated': 'AŽURIRANO',
  'autoRideError': 'GREŠKA',
  'autoRideNoActiveRoute': 'Nema aktivne rute',
  'autoRideNavigationActive': 'Navigacija aktivna',
  'autoRideSpeed': 'BRZINA',
  'autoRideRide': 'VOŽNJA',
  'autoRideArrivalBody':
      'Odredište je dostignuto. Vožnja će se završiti i automatski sačuvati.',
  'autoRideConfirmArrivalBody':
      'Ostani blizu odredišta dok Munja potvrđuje dolazak.',
  'autoRideReroutingBody':
      'Munja izračunava novu biciklističku rutu od tvoje trenutne pozicije.',
  'autoRideCheckingDeviationBody': 'Van si rute. Munja potvrđuje odstupanje.',
  'autoRideRerouteSuccessBody': 'Nova ruta, ETA i navigacija su ažurirani.',
  'autoRideRerouteFailedBody':
      'Provjeri internet vezu. Munja će pokušati ponovo pri sljedećem trajnom odstupanju.',
  'autoRideOffRouteBody': 'Skrenuo si s rute.',
  'autoRideRouteCalculatedBody':
      'Biciklistička ruta je izračunata i prikazana na karti.',
  'autoRideRouteProgress': 'Napredak rute',
  'autoRideDestinationNotSaved':
      'Odredište je odabrano, ali biciklistička ruta još nije sačuvana.',
  'altitudeShort': 'VISINA',
  'showFullRoute': 'Prikaži cijelu rutu',
  'routeStartedFromWheel': 'Ruta je pokrenuta s točka',
  'hourShort': 'h',

  // Home + Profile
  'homeBikeLoadFailed': 'Bicikl nije moguće učitati.',
  'homeNoActiveBike': 'Nema aktivnog bicikla',
  'homeNoActiveBikeBody':
      'Kreiraj ili odaberi bicikl u Opremi kako bi aktivirao svoj Digital Twin.',
  'homeOpenGear': 'Otvori Opremu',
  'homeOpeningGear': 'OTVARAM OPREMU',
  'homeActiveChallenge': 'AKTIVNI IZAZOV',
  'homeOpponent': 'protivnik',
  'homeDaysLeftSingular': 'dan preostao',
  'homeDaysLeftPlural': 'dana preostalo',
  'profileTitle': 'Profil',
  'profileRiderProfile': 'PROFIL VOZAČA',
  'profileEditProfile': 'UREDI PROFIL',
  'profileRiderDetails': 'Podaci o vozaču',
  'profileLanguage': 'JEZIK',
  'profileLevelProgress': 'NAPREDAK NIVOA',
  'profileSettingsSection': 'POSTAVKE',
  'profileDetails': 'Detalji profila',
  'profileFriends': 'Prijatelji',
  'profileRequests': 'Zahtjevi',
  'profileFriendChallengeRequests': 'Zahtjevi za prijateljstvo i izazove',
  'profileActiveChallenges': 'Aktivni izazovi',
  'profileSeeCurrentBattles': 'Pogledaj svoje trenutne duele',
  'profileAddFriend': 'Dodaj prijatelja',
  'profileChallenge': 'Izazov',
  'profileChallenges': 'Izazovi',
  'profileChallengeHub': 'Centar izazova',
  'profileFindRiders': 'Pronađi vozače',
  'profileFindRidersBody':
      'Pronađi Munja vozače, izgradi svoju ekipu i izazivajte jedni druge.',
  'profileFindAnotherRider':
      'Pronađi drugog Munja vozača i izgradi svoju ekipu.',
  'profileNoFriendsYet': 'Još nema prijatelja',
  'profileViewAll': 'Prikaži sve',
  'profileViewAllFriends': 'Prikaži sve prijatelje',
  'profileNewChallenge': 'Novi izazov',
  'profileChallengeHubBody':
      'Takmiči se s prijateljima, gradi napredak i pripremi se za Munja Monthly Specials.',
  'profileChallengeInfo':
      'Počni s 1 na 1 distancom. Više vrsta izazova, Crystal nagrade i Monthly Specials su sljedeći nivo razvoja.',
  'profileAchievements': 'Postignuća',
  'profileAchievementsCaps': 'POSTIGNUĆA',
  'profileMilestonesBody':
      'Prekretnice osvojene kroz tvoju stvarnu historiju vožnji.',
  'profileFirstRide': 'Prva vožnja',
  'profileThreeDayStreak': 'Niz od 3 dana',
  'profileComingSoon': 'dolazi u sljedećem Munja koraku.',
  'profileCreatingRiderId': 'Kreiram Rider ID...',
  'profileKm': 'KM',
  'profileStreak': 'NIZ',
  'profileRides': 'VOŽNJE',
  'profileTotalXp': 'UKUPNO XP',

  // MUNJA PRO + Challenges
  'proPurchaseFailed':
      'Kupovinu MUNJA PRO nije moguće pokrenuti. Pokušaj ponovo.',
  'proRestoreFailed': 'MUNJA PRO nije moguće vratiti. Pokušaj ponovo.',
  'proExperience': 'TVOJE MUNJA ISKUSTVO',
  'proAdvancedAnalytics': 'Napredna analitika',
  'proAdvancedAnalyticsDesc':
      'Dublji trendovi performansi, uvidi u vožnje i dugoročni napredak.',
  'proAiRideAnalysis': 'AI analiza vožnje',
  'proAiRideAnalysisDesc':
      'Pretvori podatke vožnje u korisne povratne informacije i lične uvide.',
  'proAiCoach': 'AI trener vožnje',
  'proAiCoachDesc':
      'Lični coaching na osnovu tvoje vožnje, ciljeva i napretka.',
  'proRoutePlanner': 'Napredni planer ruta',
  'proRoutePlannerDesc':
      'Pametniji alati za rute prilagođeni načinu na koji voziš.',
  'proChallenges': 'Pro izazovi',
  'proChallengesDesc':
      'Posebni izazovi, dublji ciljevi i odabrani mjesečni događaji.',
  'proSkinsFrames': 'Ekskluzivni skinovi i okviri',
  'proSkinsFramesDesc':
      'Pristupi odabranim Pro kozmetičkim opcijama dok Crystals ostaju zasebna ekonomija.',
  'proLinkedActive':
      'MUNJA PRO je povezan s tvojim računom i automatski se ažurira.',
  'proLinkedSecure':
      'Tvoj MUNJA PRO status je sigurno povezan s Munja računom.',
  'proYouArePro': 'TI IMAŠ MUNJA PRO',
  'proUnlockMore': 'OTKLJUČAJ VIŠE MUNJE',
  'proFeaturesActive': 'Tvoje Pro funkcije su aktivne na ovom računu.',
  'proMoreInsight':
      'Više uvida. Više inteligencije. Više načina da izazoveš sebe.',
  'monthlyCompletedClaimed': 'ZAVRŠENO · NAGRADA PREUZETA',
  'monthlyCompletedReady': 'ZAVRŠENO · NAGRADA SPREMNA',
  'expired': 'ISTEKLO',
  'monthlyLoading': 'Učitavam Monthly Special...',
  'monthlySpecial': 'MONTHLY SPECIAL',
  'monthlyStartsWithPro':
      'Tvoj 30-dnevni Monthly Special počinje automatski uz MUNJA PRO.',
  'monthlyActivatePro':
      'Aktiviraj MUNJA PRO da automatski pokreneš ovaj 30-dnevni Monthly Special.',
  'monthlyActivating': 'Aktiviram tvoj Monthly Special...',
  'refresh': 'OSVJEŽI',
  'claiming': 'PREUZIMAM...',
  'claimReward': 'PREUZMI NAGRADU',
  'activeMembership': 'Aktivno članstvo',
  'noActiveMembership': 'Nema aktivnog članstva',
  'monthlySubscription': 'Mjesečna pretplata',
  'premiumExperience': 'Premium Munja iskustvo',
  'freeCaps': 'BESPLATNO',
  'membershipSync':
      'Status članstva se automatski sinhronizuje s tvojim Munja računom.',
  'autoRenewing':
      'Mjesečna pretplata s automatskim obnavljanjem. Otkaži bilo kada putem Google Play.',
  'connectingStore': 'POVEZUJEM S GOOGLE PLAY...',
  'getPro': 'UZMI MUNJA PRO',
  'restoring': 'VRAĆAM...',
  'restorePurchase': 'VRATI KUPOVINU',
  'challengesTitle': 'Izazovi',
  'challengeTagline': 'TAKMIČI SE · NAPREDAK · HISTORIJA',
  'readyNextRace': 'Spreman za sljedeći duel',
  'completedAppearHistory': 'Završeni dueli će se pojaviti u tvojoj historiji.',
  'activeCaps': 'AKTIVNI',
  'historyCaps': 'HISTORIJA',
  'wins': 'POBJEDE',
  'losses': 'PORAZI',
  'draws': 'NERIJEŠENO',
  'winRate': 'POSTOTAK POBJEDA',
  'youCaps': 'TI',
  'draw': 'NERIJEŠENO',
  'victory': 'POBJEDA',
  'defeat': 'PORAZ',
  'timeExpired': 'Vrijeme je isteklo',
  'targetReached': 'Cilj je dostignut',
  'noHistory': 'Još nema historije izazova',
  'historyAppear': 'Završeni dueli će se automatski pojaviti ovdje.',
  'challengeLoadFailed': 'Podatke izazova nije moguće učitati.',
  'tryAgainCaps': 'POKUŠAJ PONOVO',
  'ending': 'Završava',
  'evenNow': 'Trenutno je potpuno izjednačeno.',
  'distanceDesc': 'Prvi vozač koji dostigne cilj pobjeđuje.',
  'rideCount': 'Broj vožnji',
  'rideCountDesc': 'Takmiči se ko će prvi završiti određeni broj vožnji.',
  'rideTime': 'Vrijeme vožnje',
  'rideTimeDesc': 'Takmiči se u ukupnom aktivnom vremenu vožnje.',
  'streakDesc': 'Izgradi najduži niz redovnih vožnji.',
  'friendsLoadFailed':
      'Tvoje Munja prijatelje nije moguće učitati. Pokušaj ponovo.',
  'newChallenge': 'Novi izazov',
  'challengeType': 'VRSTA IZAZOVA',
  'chooseRider': 'ODABERI VOZAČA',
  'sending': 'Šaljem...',
  'sendChallenge': 'Pošalji izazov',
  'challengeRewardsBalanced':
      'Nagrade izazova su balansirane kako bi Crystals ostali vrijedni.',
  'challengeARider': 'Izazovi vozača',
  'challengeIntro':
      'Takmiči se, gradi XP i radi prema Munja Crystal nagradama.',
  'monthlyLoadFailed': 'Monthly Special nije moguće učitati.',
  'rewardAlreadyClaimed': 'Ova Monthly Special nagrada je već preuzeta.',
  'completeBeforeClaim': 'Završi Monthly Special prije preuzimanja nagrade.',
  'monthlyNotFound': 'Monthly Special nije pronađen.',
  'profileNotFound': 'Tvoj Munja profil nije pronađen.',
  'rewardClaimed': 'Nagrada preuzeta.',
  'rewardClaimFailed': 'Nagradu nije moguće preuzeti. Pokušaj ponovo.',
  'loading': 'Učitavam...',
  'completed': 'Završeno',
  'thirtyDays': '30 dana',
  'proCaps': 'PRO',
  'claimed': 'PREUZETO',
  'claim': 'PREUZMI',
  'monthlyTimerInfo':
      'Tvoj 30-dnevni timer počeo je kada si aktivirao ovaj Special. Promjena kalendarskog mjeseca ga ne skraćuje.',
  'monthlyActivateInfo':
      'Aktiviraj ovaj Special kada budeš spreman. Tvoj lični 30-dnevni timer počinje tek kada pritisneš START.',
  'unlockPro': 'OTKLJUČAJ MUNJA PRO',
  'rewardClaimedCaps': 'NAGRADA PREUZETA',
  'specialActive': 'SPECIAL AKTIVAN',
  'progressCaps': 'NAPREDAK',
  'monthlyGoal': 'MJESEČNI CILJ',
  'chooseRiderFirst': 'Prvo odaberi vozača',
  'challengeSummary': 'PREGLED IZAZOVA',
  'goal': 'CILJ',
  'challengeStartsAccept': 'Izazov počinje kada tvoj prijatelj prihvati poziv.',
  'loadingFriends': 'Učitavam tvoje prijatelje...',
  'couldNotCreate': 'Nije moguće kreirati izazov',
  'tryAgain': 'Pokušaj ponovo',
  'noFriendsChallenge': 'Nema prijatelja za izazov',
  'addFriendFirst':
      'Prvo dodaj Munja prijatelja. Zatim možeš pokrenuti 1 na 1 izazov.',
  'requestsLoadFailed':
      'Zahtjeve za izazove nije moguće učitati. Pokušaj ponovo.',
  'acceptFailed': 'Izazov nije moguće prihvatiti. Pokušaj ponovo.',
  'declineFailed': 'Izazov nije moguće odbiti. Pokušaj ponovo.',
  'declineChallengeQ': 'Odbiti izazov?',
  'cancel': 'Odustani',
  'decline': 'Odbij',
  'cancelFailed': 'Izazov nije moguće otkazati. Pokušaj ponovo.',
  'cancelChallengeQ': 'Otkazati izazov?',
  'keepChallenge': 'Zadrži izazov',
  'cancelChallenge': 'Otkaži izazov',
  'challengeRequests': 'Zahtjevi za izazove',
  'incoming': 'DOLAZNI',
  'requestsForYou': 'Zahtjevi za tebe',
  'outgoing': 'POSLANI',
  'waitingResponse': 'Čeka se odgovor',
  'pending': 'NA ČEKANJU',
  'cancelling': 'Otkazujem...',
  'working': 'Obrađujem...',
  'accept': 'Prihvati',
  'loadingRequests': 'Učitavam zahtjeve za izazove...',
  'couldNotLoadRequests': 'Nije moguće učitati zahtjeve za izazove',

  // Garage / Gear / Digital Twin / Devices / Smart Brake Light
  '3dFileCouldNotOpen': '3D datoteku nije moguće otvoriti.',
  '3dModelCouldNotBeSelected': '3D model nije moguće odabrati.',
  'activate': 'Aktiviraj',
  'activeBike': 'Aktivni bicikl',
  'addAnotherProduct': 'Dodaj još jedan proizvod',
  'addBike': 'Dodaj bicikl',
  'addFirstBikeSync':
      'Dodaj svoj prvi bicikl da pokreneš sinhronizaciju Digital Twina.',
  'addImageCameraGallery': 'Dodaj sliku iz kamere ili galerije.',
  'addProduct': 'Dodaj proizvod',
  'appWorksWithoutHardware': 'Munja radi i bez hardvera.',
  'bandProductSubtitle': 'Budući wearable za upozorenja i status vožnje.',
  'batteryCatalogSubtitle': 'Budući Munja baterijski modul za povezanu opremu.',
  'bikeCouldNotActivate': 'Bicikl nije moguće aktivirati.',
  'bikeCouldNotDelete': 'Bicikl nije moguće izbrisati.',
  'bikeCouldNotSave': 'Bicikl nije moguće sačuvati.',
  'bikeCreated': 'Bicikl kreiran.',
  'bikeDeleted': 'Bicikl izbrisan.',
  'bikeFirebaseSyncInfo':
      'Tvoj bicikl je sinhronizovan s Firebaseom i tvojim Digital Twinom.',
  'bikeInfo': 'Informacije o biciklu',
  'bikeName': 'Naziv bicikla',
  'bikeSavedFileProcessFailed':
      'Bicikl je sačuvan, ali odabranu datoteku nije moguće obraditi.',
  'bikeUpdated': 'Bicikl ažuriran.',
  'bikes': 'Bicikli',
  'bleUuidMissing': 'Nedostaje BLE UUID.',
  'brakeLightAlreadyMounted':
      'Munja Smart Brake Light je već montiran na ovaj bicikl.',
  'brakeLightDashboard': 'Kontrola kočionog svjetla',
  'brakeLightDashboardSubtitle':
      'Status uživo i kontrole za tvoj Munja Smart Brake Light.',
  'brakeLightMountedTwin':
      'Munja Smart Brake Light je montiran na tvoj Digital Twin.',
  'brakeMountedOnBike': 'Smart Brake Light montiran na bicikl',
  'brakeMountedReady': 'Montiran i spreman na tvom biciklu.',
  'brakeProductSubtitle':
      'Pametno zadnje svjetlo s automatskim kočionim svjetlom i Bluetoothom.',
  'brakeReady': 'Kočiono svjetlo spremno',
  'brakingNow': 'Kočenje sada',
  'brand': 'Marka',
  'brightness': 'Jačina svjetla',
  'changeImage': 'Promijeni sliku',
  'changeModel': 'Promijeni model',
  'choose3dModel': 'Odaberi 3D model',
  'chooseFromGallery': 'Odaberi iz galerije',
  'chooseGlbGltfModel': 'Odaberi GLB ili GLTF model.',
  'chooseImage': 'Odaberi sliku',
  'chooseMunjaProductForBike': 'Odaberi Munja proizvod za ovaj bicikl.',
  'color': 'Boja',
  'comingSoonCaps': 'USKORO',
  'confirmDeleteBike': 'Jesi li siguran da želiš izbrisati ovaj bicikl?',
  'connectGear': 'Poveži opremu',
  'connectedDeviceAppearsHere': 'Tvoj povezani uređaj će se pojaviti ovdje.',
  'connectedDevices': 'Povezani uređaji',
  'connectedDevicesSubtitle': 'Veze povezane s Digital Twinom ovog bicikla.',
  'connection': 'Veza',
  'connectionStatus': 'Status veze',
  'connectionStatusSubtitle':
      'Bluetooth, Digital Twin i firmware na jednom mjestu.',
  'createBike': 'Kreiraj bicikl',
  'creating': 'Kreiram...',
  'customizeDigitalTwinCaps': 'PRILAGODI DIGITAL TWIN',
  'delete': 'Izbriši',
  'deleteBike': 'Izbriši bicikl',
  'detailsAndSetup': 'Detalji i podešavanje',
  'deviceSingular': 'Uređaj',
  'devices': 'Uređaji',
  'digitalTwin': 'Digital Twin',
  'digitalTwinReady': 'Digital Twin spreman',
  'digitalTwinReadyCaps': 'DIGITAL TWIN SPREMAN',
  'edit': 'Uredi',
  'editBike': 'Uredi bicikl',
  'enableDigitalBike3d': 'Aktiviraj svoj digitalni bicikl u 3D.',
  'enterBikeName': 'Unesi naziv bicikla.',
  'farAway': 'Daleko',
  'firmware': 'Firmware',
  'foundNearbyProducts': 'Munja proizvodi pronađeni u blizini.',
  'frameSize': 'Veličina okvira',
  'framesSkinsColors': 'Okviri, skinovi i boje',
  'garage': 'Garaža',
  'garageEmpty': 'Tvoja garaža je prazna.',
  'garageSubtitle': 'Tvoji bicikli, oprema i Digital Twin na jednom mjestu.',
  'glbModelConnected': '3D model povezan',
  'gpsCatalogSubtitle': 'Budući GPS modul za lokaciju i praćenje vožnje.',
  'hardwareInfo': 'Informacije o hardveru',
  'hardwareInfoSubtitle': 'Status uređaja, signal i informacije o firmwareu.',
  'helmet': 'Kaciga',
  'helmetProductSubtitle': 'Buduća integracija pametne kacige.',
  'imageCouldNotBeSelected': 'Sliku nije moguće odabrati.',
  'imageSavedFirebase': 'Slika je sačuvana i sinhronizovana s Firebaseom.',
  'initializingDigitalTwin': 'Pokrećem Digital Twin...',
  'isConnected': 'je povezan',
  'kidsBike': 'Dječiji bicikl',
  'lightSettings': 'Postavke svjetla',
  'lightSettingsSubtitle': 'Podesi jačinu svjetla, osjetljivost i način rada.',
  'loadingDevices': 'Učitavam uređaje...',
  'loadingProducts': 'Učitavam proizvode...',
  'loadingYourBikes': 'Učitavam tvoje bicikle...',
  'makeActive': 'Postavi kao aktivan',
  'makeBikeYours': 'Prilagodi bicikl sebi',
  'missingUuidCaps': 'NEDOSTAJE UUID',
  'mode': 'Način',
  'mountProduct': 'Montiraj proizvod',
  'mountProductFirst': 'Prvo montiraj proizvod',
  'mounted': 'Montirano',
  'mountedNoActiveConnections':
      'Proizvodi su montirani, ali nema aktivnih veza s uređajima.',
  'mountedOnBike': 'Montirano na biciklu',
  'mountedOnBikeSubtitle': 'Proizvodi trenutno montirani na tvom biciklu.',
  'mountedOnDigitalTwin': 'Montirano na Digital Twin',
  'mountedProducts': 'Montirani proizvodi',
  'mountedProductsSubtitle': 'Munja proizvodi montirani na ovaj bicikl.',
  'munjaKeepsStatusTogether':
      'Munja drži status veze, firmwarea i Digital Twina na jednom mjestu.',
  'myBikes': 'Moji bicikli',
  'newFrame': 'Novi okvir',
  'newImageReadyUpload': 'Nova slika spremna za upload',
  'newLabel': 'NOVO',
  'no3dModel': 'Nema 3D modela',
  'noDeviceConnectedYet': 'Još nema povezanog uređaja',
  'noModelCaps': 'NEMA MODELA',
  'noMountedProducts': 'Nema montiranih proizvoda',
  'noProducts': 'Nema proizvoda',
  'notEnabled': 'Nije aktivirano',
  'notInstalled': 'Nije instalirano',
  'notes': 'Bilješke',
  'off': 'Isključeno',
  'openCustomizeCaps': 'OTVORI PRILAGODBU',
  'physicalDeviceConnectsProduct':
      'Fizički uređaj se povezuje s konkretnim Munja proizvodom.',
  'physicalDeviceLinked': 'Fizički uređaj povezan s proizvodom',
  'product': 'Proizvod',
  'productStatus': 'Status proizvoda',
  'productStatusSubtitle': 'Veze, firmware i Digital Twin status.',
  'qrActivationComingSoon': 'QR aktivacija dolazi uskoro.',
  'readyToMount': 'Spremno za montažu',
  'rear': 'Nazad',
  'rideSensorCatalogSubtitle':
      'Budući senzor vožnje za kadencu, kretanje i podatke bicikla.',
  'rssi': 'RSSI',
  'saveChanges': 'Sačuvaj promjene',
  'savedProductsAppearHere': 'Sačuvani proizvodi će se pojaviti ovdje.',
  'scan': 'Skeniraj',
  'scanAgain': 'Skeniraj ponovo',
  'scanAndMountProducts': 'Skeniraj i montiraj Munja proizvode na svoj bicikl.',
  'scanBleQrLater':
      'Skeniraj putem Bluetootha sada. QR aktivacija dolazi kasnije.',
  'scanForProducts': 'Skeniraj proizvode',
  'scanMountProduct': 'Skeniraj i montiraj proizvod',
  'scanMountProductsTwin':
      'Skeniraj i montiraj Munja proizvode na svoj Digital Twin.',
  'scanningMunjaProducts': 'Skeniram Munja proizvode...',
  'sensitivity': 'Osjetljivost',
  'showroomDrag360Caps': 'SHOWROOM · POVUCI 360°',
  'signal': 'Signal',
  'skinsQuickTestCaps': 'SKINOVI · BRZI TEST',
  'smartBrakeLightCatalogSubtitle':
      'Pametno zadnje svjetlo s automatskom detekcijom kočenja i Bluetooth vezom.',
  'smartBrakeLightDescription':
      'Pametno zadnje svjetlo s automatskim kočionim svjetlom i Bluetooth vezom.',
  'supportsGlbGltf': 'Podržava GLB i GLTF.',
  'takePhoto': 'Fotografiši',
  'tapScanConnect': 'Dodirni montirani proizvod za skeniranje i povezivanje.',
  'threeDDigitalTwin': '3D Digital Twin',
  'unlockedRewardsCaps': 'OTKLJUČANE NAGRADE',
  'upToDate': 'Ažurirano',
  'update': 'Ažuriraj',
  'uploading': 'Uploadujem...',
  'useAsPrimaryBike': 'Koristi kao glavni bicikl',
  'veryClose': 'Vrlo blizu',
  'wheelSize': 'Veličina točka',
  'wrist': 'Zglob',
  'yourDigitalTwin': 'Tvoj Digital Twin',
};
