const Map<String, String> bs = {
  'appTitle': 'Munja',

  'welcome': 'Dobrodošli',
  'welcomeToMunja': 'Dobrodošli u Munju',
  'howToUseApp': 'Kako koristiti aplikaciju',
  'howToUseAppBody':
      '1. Koristi Auto Ride za automatsko praćenje.\n2. Koristi Ciljeve za ciljeve i navike.\n3. Koristi Opremu ako imaš Smart Brake Light.\n4. Otvori svoj digitalni bicikl na početnoj strani.',

  'chooseAvatarMode': 'Odaberi avatar način',
  'avatarModeSubtitle': 'Učini aplikaciju ličnijom prije početka.',
  'setupBeforeStart': 'Podešavanje prije početka',
  'setupBeforeStartSubtitle': 'Dodaj svoje podatke prije ulaska u aplikaciju.',
  'name': 'Ime',
  'age': 'Godine',
  'city': 'Grad',
  'startApp': 'Pokreni aplikaciju',
  'back': 'Nazad',
  'next': 'Dalje',
  'appMode': 'Način aplikacije',

  'home': 'Početna',
  'ride': 'Vožnja',
  'challenge': 'Ciljevi',
  'products': 'Oprema',
  'goals': 'Ciljevi',
  'gear': 'Oprema',
  'profile': 'Profil',
  'routes': 'Rute',
  'coach': 'Trener',
  'analytics': 'Analitika',

  'ready': 'Spremno',
  'live': 'Uživo',
  'route': 'Ruta',
  'time': 'Vrijeme',
  'level': 'Nivo',
  'distance': 'Udaljenost',
  'speed': 'Brzina',
  'duration': 'Trajanje',
  'avg': 'Prosjek',
  'avgSpeed': 'Prosječna brzina',
  'calories': 'Kalorije',
  'routePoints': 'Tačke rute',
  'total': 'Ukupno',
  'last': 'Zadnje',
  'lastRide': 'Zadnja vožnja',
  'rides': 'Vožnje',
  'thisWeek': 'Ove sedmice',
  'weeklyGoal': 'Sedmični cilj',

  'digital_twin_ready': 'Digitalni blizanac spreman',
  'gps': 'GPS',
  'bluetooth': 'Bluetooth',
  'battery': 'Baterija',
  'active': 'Aktivno',
  'inactive': 'Neaktivno',
  'hold_to_start': 'Drži za start',
  'hold_to_stop': 'Drži za stop',
  'smart_brake_light_connected': 'Smart Lighting Brake povezan',
  'tap_bike_to_manage_gear': 'Dodirni bicikl za upravljanje opremom',

  'goodMorning': 'Dobro jutro',
  'goodAfternoon': 'Dobar dan',
  'goodEvening': 'Dobro veče',
  'homeHeadline': 'Tvoj bicikl živi digitalno',
  'startAutoRideBody':
      'Drži kristal za početak vožnje i otvori svoj digitalni bicikl.',
  'streak': 'Niz',
  'days': 'dana',

  'greenerTransport': 'Zeleniji transport',
  'greenImpact': 'Tvoj zeleni uticaj',
  'greenImpactSubtitle':
      'Kada odabereš bicikl umjesto auta, pomažeš smanjiti CO₂ i nepotrebne vožnje autom.',
  'co2Saved': 'Ušteđeni CO₂',
  'carKmAvoided': 'Izbjegnuti auto-km',
  'greenImpactPositive':
      'Već si napravio razliku ove sedmice. Svaka vožnja pomaže smanjiti saobraćaj, potrošnju goriva i CO₂.',
  'greenImpactStart':
      'Pokreni prvu vožnju i vidi koliko CO₂ možeš uštedjeti birajući bicikl umjesto auta.',
  'monthlyOverview': 'Mjesečni pregled',
  'monthlyOverviewSubtitle':
      'Pogledaj napredak iz mjeseca u mjesec kroz udaljenost i zeleniji transport.',
  'totalSixMonths': 'Ukupno 6 mjeseci',
  'totalCo2Saved': 'Ukupno ušteđeni CO₂',

  'hardware': 'Hardware',
  'hardwareNearby': 'Tvoj Smart Brake Light je u blizini.',
  'noHardwareFound':
      'Trenutno nema pronađenog hardware-a. Aplikacija i dalje može raditi samostalno.',
  'allProducts': 'Sva oprema',
  'smartBrakeLight': 'Smart Brake Light',
  'openStatusSensitivityConnection':
      'Otvori status, osjetljivost i informacije o vezi',
  'scanSaveManageDevices': 'Skeniraj, sačuvaj i upravljaj Munja uređajima',
  'locationPermissionsMissing': 'Nedostaju dozvole za lokaciju',
  'bluetoothPermissionMissing': 'Nedostaje Bluetooth ili dozvola za lokaciju',
  'tryingToConnect': 'Pokušavam povezivanje…',
  'noSavedDeviceYet': 'Još nema sačuvanog uređaja',
  'connected': 'Povezano',
  'disconnected': 'Prekinuto',
  'couldNotConnect': 'Nije moguće povezati',
  'connecting': 'POVEZIVANJE…',
  'notConnected': 'NIJE POVEZANO',
  'connectNow': 'Poveži sada',
  'brakeLightSensitivity': 'Osjetljivost kočionog svjetla',
  'sensitivityHint': 'Nisko = brže reaguje · Visoko = zahtijeva jače kočenje',
  'hardwareFound': 'Hardware pronađen',
  'softwareOnly': 'Samo software',

  'autoRide': 'Auto Ride',
  'automaticTracking': 'Automatsko praćenje',
  'automaticTrackingSubtitle':
      'Koristi dva prsta za zumiranje na mapi, a vožnja se automatski zaustavlja nakon 30 sekundi ispod granice zaustavljanja.',
  'monitoring': 'Praćenje',
  'notStarted': 'NIJE POKRENUTO',
  'stopMonitoring': 'Zaustavi praćenje',
  'startAutoMode': 'Pokreni auto način',
  'stopTracking': 'Zaustavi tracking',
  'openAutoRide': 'Otvori Auto Ride',

  'map': 'Mapa',
  'mapSubtitle':
      'Koristi dva prsta za zumiranje. Možeš koristiti i dugmad ili se vratiti na trenutnu lokaciju.',
  'myLocation': 'Moja lokacija',
  'yourPosition': 'Tvoja pozicija',
  'recentRides': 'Nedavne vožnje',
  'recentRidesSubtitle':
      'Sačuvane vožnje zadržavaju svoju rutu. Dodirni vožnju da je vidiš na mapi.',
  'noRidesSavedYet': 'Još nema sačuvanih vožnji.',
  'rideRoute': 'Ruta vožnje',
  'start': 'Start',
  'finish': 'Cilj',

  'bikeChallenge': 'Biciklistički ciljevi',
  'yourChallenge': 'Tvoj cilj',
  'yourChallengeSubtitle': 'Postavi rok i napravi od biciklizma stalnu naviku.',
  'setChallengeDate': 'Postavi datum za svoj cilj.',
  'deadlinePassed': 'Rok je prošao — postavi novi 💪',
  'itIsToday': 'To je danas! 🚴',
  'daysLeft': 'dana preostalo',
  'setDate': 'Postavi datum',
  'changeDate': 'Promijeni datum',
  'startChallenge': 'Pokreni cilj',
  'planAndGoal': 'Plan i cilj',
  'planAndGoalSubtitle': 'Odaberi kada obično voziš i prilagodi sedmični cilj.',
  'bikeToWork': 'Biciklom na posao',
  'afterWork': 'Poslije posla',
  'weekend': 'Vikend',
  'morning': 'Jutro',
  'yourPlan': 'Tvoj plan',
  'openGuide': 'Otvori vodič',
  'challengeGuide': 'Vodič za ciljeve',
  'dailySteps': 'Dnevni koraci',
  'mindset': 'Mentalitet',
  'startSetGoal': 'Počni — postavi cilj',
  'writeDownDate': 'Zapiši datum.',
  'chooseRideTime': 'Odaberi kada želiš voziti tokom sedmice.',
  'makeStartEasy': 'Učini početak što lakšim.',
  'findRoutineTime': 'Nađi 10–20 minuta u svojoj rutini.',
  'takeShortRide': 'Reci sebi: Danas ću samo kratko provozati.',
  'repeatHabit': 'Ponavljaj dok ne postane navika.',
  'focusProgress': 'Fokusiraj se na napredak, ne na savršenstvo.',
  'holdSmallWins': 'Drži se malih pobjeda.',
  'importantAction': 'Najvažnije je krenuti.',

  'profileSettings': 'Avatar i postavke',
  'riderIdentity': 'Tvoj biciklistički identitet',
  'riderIdentitySubtitle': 'Odaberi avatar način i ažuriraj svoje podatke.',
  'saveAvatarProfile': 'Sačuvaj avatar i profil',
  'profileSaved': 'Avatar i profil su sačuvani',

  'myProducts': 'Moja oprema',
  'nearby': 'U blizini',
  'scanProductsSubtitle': 'Skeniraj Munja opremu oko sebe.',
  'noProductsNearby': 'Nema opreme u blizini.',
  'savedProducts': 'Sačuvana oprema',
  'savedProductsSubtitle': 'Uređaji koje si ranije sačuvao.',
  'noSavedProducts': 'Još nema sačuvane opreme.',
  'saved': 'Sačuvano',
  'save': 'Sačuvaj',
  'add': 'Dodaj',

  'classicRider': 'Klasični vozač',
  'speedMode': 'Brzi način',
  'ecoMode': 'Eko način',
  'challengeMode': 'Ciljni način',
  'nightRide': 'Noćna vožnja',
  'safeRider': 'Siguran vozač',

  'smartRoutePlanner': 'Pametni planer ruta',
  'smartRouteAi': 'Smart Route AI',
  'searchAddress': 'Pretraži adresu...',
  'destination': 'Odredište',
  'enterWhereYouWantToRide': 'Unesi gdje želiš voziti.',
  'generateRoute': 'Generiši rutu',
  'generating': 'Generišem...',
  'searching': 'Pretražujem...',
  'routePreview': 'Pregled rute',
  'addressSearchNow':
      'Pretraga adrese sada. Pravi road-routing API dolazi kasnije.',
  'whyThisRoute': 'Zašto ova ruta?',
  'munjaScoresRoute': 'Munja je ocjenjuje na osnovu tvog stila.',
  'safety': 'Sigurnost',
  'scenic': 'Lijepa ruta',
  'fitness': 'Fitness',
  'useThisRoute': 'Koristi ovu rutu',
  'generateNewSuggestions': 'Generiši nove prijedloge',
  'routeGenerated': 'Ruta generisana',
  'addressNotFound': 'Adresa nije pronađena.',
  'enterAddressFirst': 'Prvo unesi adresu.',
  'couldNotFindAddress': 'Nije moguće pronaći tu adresu.',
  'selectedAndSaved': 'odabrana i sačuvana.',

  'aiRideCoach': 'AI trener vožnje',
  'personalRideIntelligence':
      'Lična inteligencija vožnje, oporavak i savjeti za tempo.',
  'readiness': 'Spremnost',
  'fatigue': 'Umor',
  'consistency': 'Dosljednost',
  'todayPlan': 'Današnji plan',
  'recommendedRecentHistory': 'Preporučeno na osnovu nedavne historije vožnji.',
  'rideType': 'Tip vožnje',
  'coachIntelligence': 'Coach inteligencija',
  'whatMunjaNotices': 'Šta Munja primjećuje o tvojoj vožnji.',
  'adaptiveRecommendation': 'Prilagodljiva preporuka',
  'safetyLayer': 'Sigurnosni sloj',
  'performanceTrend': 'Trend performansi',
  'coachTips': 'Savjeti trenera',
  'smallActionsBetterRide': 'Male radnje za bolju vožnju.',
  'useRecommendation': 'Koristi preporuku',
  'coachRecommendationActivated': 'Preporuka trenera je aktivirana.',

  'monthlyProgress': 'Mjesečni napredak',
  'lastSixMonthsRiding': 'Zadnjih 6 mjeseci vožnje.',
  'consistencyCreatesResults': 'Dosljednost stvara rezultate.',
  'latestSavedTrips': 'Tvoje zadnje sačuvane vožnje.',
  'longest': 'Najduža',
  'achievements': 'Postignuća',
  'progressUnlocked': 'Napredak otključan iz ove vožnje.',
  'yourRidePathWasSaved': 'Tvoja ruta vožnje je sačuvana.',

  'openMap': 'Otvori mapu',
  'stop': 'Stop',
  'aiCoachActivated': 'AI trener aktiviran',
  'savedToMyProducts': 'sačuvano u Moju opremu',
};
