const Map<String, String> da = {
  'appTitle': 'Munja',

  'welcome': 'Velkommen',
  'welcomeToMunja': 'Velkommen til Munja',
  'howToUseApp': 'Sådan bruger du appen',
  'howToUseAppBody':
      '1. Brug Auto Ride til automatisk tracking.\n2. Brug Mål til mål og vaner.\n3. Brug Udstyr hvis du har en Smart Brake Light.\n4. Åbn din digitale cykel på forsiden.',

  'chooseAvatarMode': 'Vælg din avatar-tilstand',
  'avatarModeSubtitle': 'Gør appen mere personlig før du starter.',
  'setupBeforeStart': 'Opsætning før start',
  'setupBeforeStartSubtitle': 'Tilføj dine oplysninger før du går ind i appen.',
  'name': 'Navn',
  'age': 'Alder',
  'city': 'By',
  'startApp': 'Start app',
  'back': 'Tilbage',
  'next': 'Næste',
  'appMode': 'App-tilstand',

  'home': 'Hjem',
  'ride': 'Tur',
  'challenge': 'Mål',
  'products': 'Udstyr',
  'goals': 'Mål',
  'gear': 'Udstyr',
  'profile': 'Profil',
  'routes': 'Ruter',
  'coach': 'Coach',
  'analytics': 'Analytics',

  'ready': 'Klar',
  'live': 'Live',
  'route': 'Rute',
  'time': 'Tid',
  'level': 'Niveau',
  'distance': 'Distance',
  'speed': 'Hastighed',
  'duration': 'Varighed',
  'avg': 'Gns.',
  'avgSpeed': 'Gns. hastighed',
  'calories': 'Kalorier',
  'routePoints': 'Rutepunkter',
  'total': 'I alt',
  'last': 'Seneste',
  'lastRide': 'Seneste tur',
  'rides': 'Ture',
  'thisWeek': 'Denne uge',
  'weeklyGoal': 'Ugentligt mål',

  'digital_twin_ready': 'Digital tvilling klar',
  'gps': 'GPS',
  'bluetooth': 'Bluetooth',
  'battery': 'Batteri',
  'active': 'Aktiv',
  'inactive': 'Inaktiv',
  'hold_to_start': 'Hold for at starte',
  'hold_to_stop': 'Hold for at stoppe',
  'smart_brake_light_connected': 'Smart Lighting Brake forbundet',
  'tap_bike_to_manage_gear': 'Tryk på cyklen for at administrere udstyr',

  'goodMorning': 'Godmorgen',
  'goodAfternoon': 'God eftermiddag',
  'goodEvening': 'God aften',
  'homeHeadline': 'Din cykel lever digitalt',
  'startAutoRideBody':
      'Hold krystallet for at starte din tur og åbne din digitale cykel.',
  'streak': 'Stime',
  'days': 'dage',

  'greenerTransport': 'Grønnere transport',
  'greenImpact': 'Din grønne effekt',
  'greenImpactSubtitle':
      'Når du vælger cyklen i stedet for bilen, hjælper du med at reducere CO₂ og unødvendige bilture.',
  'co2Saved': 'CO₂ sparet',
  'carKmAvoided': 'Bil-km undgået',
  'greenImpactPositive':
      'Du har allerede gjort en forskel denne uge. Hver tur hjælper med at reducere trafik, brændstofforbrug og CO₂-udledning.',
  'greenImpactStart':
      'Start din første tur og se hvor meget CO₂ du kan spare ved at vælge cyklen i stedet for bilen.',
  'monthlyOverview': 'Månedlig oversigt',
  'monthlyOverviewSubtitle':
      'Se din fremgang måned for måned med distance og grønnere transport.',
  'totalSixMonths': 'I alt 6 måneder',
  'totalCo2Saved': 'CO₂ sparet i alt',

  'hardware': 'Hardware',
  'hardwareNearby': 'Din Smart Brake Light er i nærheden.',
  'noHardwareFound':
      'Ingen hardware fundet lige nu. Appen kan stadig køre alene.',
  'allProducts': 'Alle produkter',
  'smartBrakeLight': 'Smart Brake Light',
  'openStatusSensitivityConnection':
      'Åbn status, følsomhed og forbindelsesinfo',
  'scanSaveManageDevices': 'Scan, gem og administrer dine Munja-enheder',
  'locationPermissionsMissing': 'Lokationstilladelser mangler',
  'bluetoothPermissionMissing': 'Bluetooth eller lokationstilladelse mangler',
  'tryingToConnect': 'Prøver at forbinde…',
  'noSavedDeviceYet': 'Ingen gemt enhed endnu',
  'connected': 'Forbundet',
  'disconnected': 'Afbrudt',
  'couldNotConnect': 'Kunne ikke forbinde',
  'connecting': 'FORBINDER…',
  'notConnected': 'IKKE FORBUNDET',
  'connectNow': 'Forbind nu',
  'brakeLightSensitivity': 'Bremselygte-følsomhed',
  'sensitivityHint':
      'Lav = reagerer hurtigere · Høj = kræver hårdere bremsning',
  'hardwareFound': 'Hardware fundet',
  'softwareOnly': 'Kun software',

  'autoRide': 'Auto Ride',
  'automaticTracking': 'Automatisk tracking',
  'automaticTrackingSubtitle':
      'Knib for at zoome på kortet, og turen stopper automatisk efter 30 sekunder under stopgrænsen.',
  'monitoring': 'Overvågning',
  'notStarted': 'IKKE STARTET',
  'stopMonitoring': 'Stop overvågning',
  'startAutoMode': 'Start auto-tilstand',
  'stopTracking': 'Stop tracking',
  'openAutoRide': 'Åbn Auto Ride',

  'map': 'Kort',
  'mapSubtitle':
      'Brug to fingre til at zoome. Du kan også bruge knapperne eller hoppe tilbage til din nuværende placering.',
  'myLocation': 'Min placering',
  'yourPosition': 'Din position',
  'recentRides': 'Seneste ture',
  'recentRidesSubtitle':
      'Gemte ture beholder deres rute. Tryk på en tur for at se den på kortet.',
  'noRidesSavedYet': 'Ingen ture gemt endnu.',
  'rideRoute': 'Turrute',
  'start': 'Start',
  'finish': 'Slut',

  'bikeChallenge': 'Cykelmål',
  'yourChallenge': 'Dit mål',
  'yourChallengeSubtitle': 'Sæt en deadline og gør cykling til en fast vane.',
  'setChallengeDate': 'Sæt en dato for dit mål.',
  'deadlinePassed': 'Deadline er passeret — sæt en ny 💪',
  'itIsToday': 'Det er i dag! 🚴',
  'daysLeft': 'dage tilbage',
  'setDate': 'Sæt dato',
  'changeDate': 'Skift dato',
  'startChallenge': 'Start mål',
  'planAndGoal': 'Plan og mål',
  'planAndGoalSubtitle':
      'Vælg hvornår du normalt cykler, og justér dit ugentlige mål.',
  'bikeToWork': 'Cykel til arbejde',
  'afterWork': 'Efter arbejde',
  'weekend': 'Weekend',
  'morning': 'Morgen',
  'yourPlan': 'Din plan',
  'openGuide': 'Åbn guide',
  'challengeGuide': 'Målguide',
  'dailySteps': 'Daglige trin',
  'mindset': 'Mindset',
  'startSetGoal': 'Start — sæt dit mål',
  'writeDownDate': 'Skriv en dato ned.',
  'chooseRideTime': 'Vælg hvornår du vil cykle i løbet af ugen.',
  'makeStartEasy': 'Gør starten så nem som muligt.',
  'findRoutineTime': 'Find 10–20 minutter i din rutine.',
  'takeShortRide': 'Sig til dig selv: Jeg tager bare en kort tur i dag.',
  'repeatHabit': 'Gentag det indtil det bliver en vane.',
  'focusProgress': 'Fokusér på fremgang, ikke perfektion.',
  'holdSmallWins': 'Hold fast i de små sejre.',
  'importantAction': 'Det vigtigste er at handle.',

  'profileSettings': 'Avatar & indstillinger',
  'riderIdentity': 'Din cykelidentitet',
  'riderIdentitySubtitle':
      'Vælg en avatar-tilstand og opdater dine oplysninger.',
  'saveAvatarProfile': 'Gem avatar & profil',
  'profileSaved': 'Avatar og profil gemt',

  'myProducts': 'Mit udstyr',
  'nearby': 'I nærheden',
  'scanProductsSubtitle': 'Scan efter Munja-produkter omkring dig.',
  'noProductsNearby': 'Ingen produkter fundet i nærheden.',
  'savedProducts': 'Gemt udstyr',
  'savedProductsSubtitle': 'Enheder du tidligere har gemt.',
  'noSavedProducts': 'Intet gemt udstyr endnu.',
  'saved': 'Gemt',
  'save': 'Gem',
  'add': 'Tilføj',

  'classicRider': 'Klassisk cyklist',
  'speedMode': 'Farttilstand',
  'ecoMode': 'Økotilstand',
  'challengeMode': 'Måltilstand',
  'nightRide': 'Nattur',
  'safeRider': 'Sikker cyklist',

  'smartRoutePlanner': 'Smart ruteplanlægger',
  'smartRouteAi': 'Smart Route AI',
  'searchAddress': 'Søg adresse...',
  'destination': 'Destination',
  'enterWhereYouWantToRide': 'Indtast hvor du vil cykle hen.',
  'generateRoute': 'Generér rute',
  'generating': 'Genererer...',
  'searching': 'Søger...',
  'routePreview': 'Rutevisning',
  'addressSearchNow':
      'Adressesøgning nu. Rigtig road-routing API kommer senere.',
  'whyThisRoute': 'Hvorfor denne rute?',
  'munjaScoresRoute': 'Munja vurderer den ud fra din stil.',
  'safety': 'Sikkerhed',
  'scenic': 'Naturskøn',
  'fitness': 'Fitness',
  'useThisRoute': 'Brug denne rute',
  'generateNewSuggestions': 'Generér nye forslag',
  'routeGenerated': 'Rute genereret',
  'addressNotFound': 'Adresse ikke fundet.',
  'enterAddressFirst': 'Indtast først en adresse.',
  'couldNotFindAddress': 'Kunne ikke finde den adresse.',
  'selectedAndSaved': 'valgt og gemt.',

  'aiRideCoach': 'AI Ride Coach',
  'personalRideIntelligence':
      'Personlig cykelintelligens, restitution og tempo-vejledning.',
  'readiness': 'Klarhed',
  'fatigue': 'Træthed',
  'consistency': 'Konsistens',
  'todayPlan': 'Dagens plan',
  'recommendedRecentHistory': 'Anbefalet baseret på din seneste turhistorik.',
  'rideType': 'Turtype',
  'coachIntelligence': 'Coach-intelligens',
  'whatMunjaNotices': 'Hvad Munja lægger mærke til ved din cykling.',
  'adaptiveRecommendation': 'Adaptiv anbefaling',
  'safetyLayer': 'Sikkerhedslag',
  'performanceTrend': 'Præstationstrend',
  'coachTips': 'Coach-tips',
  'smallActionsBetterRide': 'Små handlinger for en bedre tur.',
  'useRecommendation': 'Brug anbefaling',
  'coachRecommendationActivated': 'Coach-anbefaling aktiveret.',

  'monthlyProgress': 'Månedlig fremgang',
  'lastSixMonthsRiding': 'De sidste 6 måneders cykling.',
  'consistencyCreatesResults': 'Konsistens skaber resultater.',
  'latestSavedTrips': 'Dine seneste gemte ture.',
  'longest': 'Længste',
  'achievements': 'Præstationer',
  'progressUnlocked': 'Fremgang låst op fra denne tur.',
  'yourRidePathWasSaved': 'Din turrute blev gemt.',

  'openMap': 'Åbn kort',
  'stop': 'Stop',
  'aiCoachActivated': 'AI Coach aktiveret',
  'savedToMyProducts': 'gemt i Mit udstyr',

  // Bike Customize
  'customize': 'Tilpas',
  'skins': 'Skins',
  'frame': 'Frame',
  'livePreview': 'Live preview',
  'showroom': 'Showroom',
  'dragToRotateStageSync': 'Træk for at rotere · scene synkroniseret',
  'frameTrail': 'Trail',
  'frameEnduro': 'Enduro',
  'frameRace': 'Race',
  'frameUrban': 'Urban',
  'colorMidnight': 'Midnight',
  'colorDeepBlack': 'Dyb sort',
  'colorMunjaMint': 'Munja Mint',
  'colorSignature': 'Signatur',
  'colorArctic': 'Arctic',
  'colorCleanWhite': 'Ren hvid',
  'colorVelocity': 'Velocity',
  'colorElectricBlue': 'Elektrisk blå',
  'colorPulse': 'Pulse',
  'colorPerformanceRed': 'Performance-rød',
  'colorForest': 'Forest',
  'colorNatureGreen': 'Naturgrøn',
  'skinStandard': 'Standard',
  'skinStandardSubtitle': 'Gratis farver under Frame',
  'skinBrushedMetal': 'Brushed Metal',
  'skinPremiumMetal': 'Premium metal',
  'skinCarbonFibre': 'Carbon Fibre',
  'skinPremiumCarbon': 'Premium carbon',
  'skinGold': 'Gold',
  'skinPremiumFinish': 'Premium finish',
  'skinIceSilver': 'Ice Silver',
  'skinColdMetallic': 'Kold metallic',
  'skinLavaRed': 'Lava Red',
  'skinPerformanceFinish': 'Performance finish',
  'skinMattBlack': 'Matt Black',
  'skinStealthFinish': 'Stealth finish',
  'skinNeonGreen': 'Neon Green',
  'skinElectricFinish': 'Elektrisk finish',
  'skinTitanium': 'Titanium',
  'skinEliteMetal': 'Elite metal',
  'owned': 'Ejet',
  'pro': 'Pro',
  'locked': 'Låst',
  'munjaCrystals': 'Munja Crystals',
  'munjaPro': 'Munja Pro',
  'proExclusive': 'Kun til Pro',
  'crystalSkinDescription': 'Dette skin kan låses op med Munja Crystals. Købsflowet kobles på i næste store step.',
  'proSkinDescription': 'Dette skin bliver en del af Munja Pro. Abonnementsflowet kobles på senere.',
  'challengeReward': 'Challenge-belønning',
  'rewardSkinDescription': 'Dette skin låses op gennem en challenge eller achievement.',
  'gotIt': 'Forstået',
  'comingNext': 'Kommer næste',
  'freeFrameColorActive': 'Gratis frame-farve aktiv. Premium skin er slået fra.',
  'frameColorSyncFailed': 'Frame-farven kunne ikke synkroniseres. Prøv igen.',
  'frameChangeFailed': 'Frame kunne ikke skiftes. Prøv igen.',
  'livePremiumPreview': 'Live premium preview',
  'materialPending': 'materiale afventer',
  'activeAndSynced': 'Aktiv og synkroniseret',
  'skinActivationFailed': 'Skin kunne ikke aktiveres. Prøv igen.',
  'skinsSectionSubtitle': 'Premium-materialer vises direkte på din 3D-cykel · gratis farver findes under Frame.',
  'livePremiumPreviews': 'Live premium previews',
  'skinStoreComingSoonMessage': 'Skin Store-kataloget er klar. Køb og oplåsning kobles på som næste step.',
  'munjaSkinStore': 'Munja Skin Store',
  'premiumProRewardSkins': 'Premium-, Pro- og reward-skins',
  'equipped': 'Aktiveret',
  'proOnly': 'Kun Pro',
  'frameSectionSubtitle': 'Vælg geometri og finish uden at forlade showroomet.',
  'frameFinish': 'Finish',
  'comingSoon': 'Snart',

  // Ride Setup / Route Planner
  'rideSetupSearchDestination': 'Søg destination',
  'rideSetupCreateRoundTrip': 'Lav en rundtur',
  'rideSetupGetRouteSuggestions': 'Få ruteforslag',
  'rideSetupStartFreeRide': 'Start fri tur',
  'rideSetupUseDestination': 'Brug destination',
  'rideSetupCreateRoundTripButton': 'Lav rundtur',
  'rideSetupShowSuggestions': 'Vis ruteforslag',
  'rideSetupUseSelectedSuggestion': 'Brug valgt forslag',
  'rideSetupAddressSuggestionsUnavailable': 'Adresseforslag kunne ikke hentes lige nu.',
  'rideSetupGooglePlacesLocalFallback': 'Google Places kunne ikke nås – viser lokale forslag.',
  'rideSetupShowingLocalSuggestions': 'Viser lokale forslag.',
  'rideSetupGpsUnavailable': 'Munja kunne ikke finde din GPS-position. Kontrollér placeringstilladelsen og prøv igen.',
  'rideSetupNoGoodSuggestions': 'Munja fandt ingen gode forslag i området.',
  'rideSetupChooseBestRoute': 'Vælg den rute, der passer dig bedst.',
  'rideSetupSuggestionsLoadFailed': 'Ruteforslag kunne ikke hentes.',
  'rideSetupSuggestionsLoadFailedRetry': 'Ruteforslag kunne ikke hentes. Prøv igen.',
  'rideSetupChooseSuggestionFirst': 'Vælg et ruteforslag først.',
  'rideSetupEnterAndChooseDestination': 'Indtast og vælg en destination.',
  'rideSetupChooseAddressFromSuggestions': 'Vælg en adresse fra forslagene.',
  'rideSetupTitle': 'Tur',
  'rideSetupHowRide': 'Hvordan vil du cykle?',
  'rideSetupChooseOneOption': 'Vælg én mulighed. Munja viser kun de valg, du har brug for.',
  'rideSetupHowFar': 'Hvor langt?',
  'rideSetupChooseApproxDistance': 'Vælg cirka hvor lang turen skal være.',
  'rideSetupHowRouteFeel': 'Hvordan skal ruten føles?',
  'rideSetupRouteStyleSubtitle': 'Munja tilpasser ruten efter din stil.',
  'rideSetupFindingSuggestions': 'Finder forslag...',
  'rideSetupPreparing': 'Forbereder...',
  'rideSetupProPlannerActive': 'MUNJA PRO · Avanceret ruteplanlægger aktiv',
  'rideSetupProRequired': 'Denne rutetype kræver MUNJA PRO',
  'rideSetupIntroTitle': 'Hvordan vil du cykle i dag?',
  'rideSetupIntroSubtitle': 'Vælg turtype. Resten kommer først frem, når det er relevant.',
  'rideSetupDestination': 'Destination',
  'rideSetupDestinationSubtitle': 'Vælg hvor du vil hen',
  'rideSetupRoundTrip': 'Rundtur',
  'rideSetupRoundTripSubtitle': 'Ud og hjem til samme sted',
  'rideSetupMunjaSuggestions': 'Munja forslag',
  'rideSetupMunjaSuggestionsSubtitle': 'Lad Munja finde turen',
  'rideSetupFreeRide': 'Fri tur',
  'rideSetupFreeRideSubtitle': 'Ingen plan. Bare kør.',
  'rideSetupChange': 'SKIFT',
  'rideSetupWhereTo': 'Hvor vil du hen?',
  'rideSetupSearchAddressOrDestination': 'Søg efter en adresse eller destination.',
  'rideSetupFreeHeroTitle': 'Ingen rute. Bare kør.',
  'rideSetupFreeHeroBody': 'Munja registrerer stadig din tur, distance og tid.',
  'rideSetupChooseRideTypeContinue': 'Vælg en turtype for at fortsætte',
  'rideSetupWheelReadyFree': 'Hjulet er klar til fri tur',
  'rideSetupWheelReadyPlanning': 'Hjulet forbliver klar, mens du planlægger',
  'rideSetupSearchAddress': 'Søg adresse',
  'rideSetupBackToStart': 'Tilbage til start',
  'rideSetupSuggestions': 'Forslag',
  'rideSetupMunjaRecommends': 'Munja anbefaler',
  'rideSetupNoPlannedRoute': 'Ingen planlagt rute',
  'rideSetupRequiresPro': 'Kræver Munja Pro',
  'rideSetupAddressHint': 'Indtast adresse eller destination',
  'rideSetupClear': 'Ryd',
  'rideSetupLocalTestMode': 'Testtilstand: lokale adresseforslag. Tilføj GOOGLE_MAPS_API_KEY for Google-forslag.',
  'rideSetupNoAddresses': 'Ingen adresser fundet.',
  'rideSetupNoLocalAddresses': 'Ingen lokale testadresser fundet.',
  'rideSetupChooseDestination': 'Vælg destination',
  'rideSetupEnterAddressRoute': 'Indtast en adresse for at finde en rute.',
  'rideSetupAutomaticRoundTrip': 'Automatisk rundtur',
  'rideSetupRoundTripInfo': 'Munja gemmer din valgte distance og rutetype.',
  'rideSetupSuggestionsInfo': 'Munja finder flere cykelruter omkring dig og matcher dem med din ønskede distance.',
  'rideSetupFreeRideInfo': 'Start turregistrering uden en fast destination.',
  'rideSetupAround': 'Omkring',
  'rideSetupFindNewSuggestions': 'Find nye forslag',
  'rideSetupAnalyzingRoads': 'Munja analyserer cykelveje omkring dig...',
  'rideSetupRoute': 'Rute',
  'rideSetupVeryCloseDistance': 'Meget tæt på din ønskede distance',
  'rideSetupKmFromGoal': 'km fra dit mål',
  'rideSetupBikeRoad': 'Landevej',
  'rideSetupBikeFamily': 'Familie',
  'rideSetupBikeNature': 'Natur',
  'rideSetupBikeQuiet': 'Rolig',
  'rideSetupBikeQuietRoads': 'Rolige veje',
  'rideSetupSelectedRide': 'Din valgte tur',

  // Ride Summary + Auto Ride
  'rideSummaryAiAnalysis': 'AI-turanalyse',
  'rideSummaryAiProSubtitle': 'Personlig Pro-analyse baseret på denne tur og din turhistorik.',
  'rideSummaryAiFreeSubtitle': 'En enkel turopsummering. MUNJA PRO tilføjer personlig historik og dybere anbefalinger.',
  'rideSummaryAnalyzing': 'Analyserer din tur...',
  'rideSummaryAnalysisUnavailable': 'Turanalysen er ikke tilgængelig lige nu.',
  'rideSummaryProAnalysis': 'MUNJA PRO ANALYSE',
  'rideSummaryRideRecap': 'MUNJA TUROPSUMMERING',
  'rideSummaryConsistency': 'KONSISTENS',
  'rideSummaryTrend': 'TREND',
  'rideSummaryFaster': 'HURTIGERE',
  'rideSummaryLonger': 'LÆNGERE',
  'rideSummarySteady': 'STABIL',
  'rideSummaryHeader': 'MUNJA OVERSIGT',
  'rideRewards': 'TURBELØNNINGER',
  'loadingEarnedRewards': 'Indlæser optjente belønninger...',
  'noCrystalRewardRide': 'Denne tur gav ingen Crystal-belønning.',
  'rideCompletedReward': 'Tur gennemført',
  'firstRideBonus': 'Bonus for første tur',
  'totalEarned': 'OPTJENT I ALT',
  'crystalRewardsLoadFailed': 'Crystal-belønninger kunne ikke indlæses.',
  'retry': 'PRØV IGEN',
  'speedUnitShort': 'km/t',
  'autoRideArrivedSaved': 'Du er ankommet. Turen afsluttes og gemmes.',
  'free': 'GRATIS',
  'autoRideLoopStarted': 'Rundtur startet · følg ruten',
  'autoRideArrived': 'Du er ankommet',
  'autoRideConfirmingArrival': 'Bekræfter ankomst...',
  'autoRideRecalculating': 'Genberegner rute...',
  'autoRideCheckingRoute': 'Kontrollerer ruten...',
  'autoRideNewRouteReady': 'Ny rute er klar',
  'autoRideCouldNotRecalculate': 'Kunne ikke genberegne',
  'autoRideChooseDestinationHome': 'Vælg en destination fra Home',
  'autoRideRouteActive': 'RUTEN ER AKTIV',
  'autoRideThere': 'FREMME',
  'autoRideWait': 'VENT',
  'autoRideOffRoute': 'VÆK FRA RUTEN',
  'autoRideUpdated': 'OPDATERET',
  'autoRideError': 'FEJL',
  'autoRideNoActiveRoute': 'Ingen aktiv rute',
  'autoRideNavigationActive': 'Navigation aktiv',
  'autoRideSpeed': 'FART',
  'autoRideRide': 'TUR',
  'autoRideArrivalBody': 'Destinationen er nået. Turen afsluttes og gemmes automatisk.',
  'autoRideConfirmArrivalBody': 'Bliv tæt på destinationen, mens Munja bekræfter ankomsten.',
  'autoRideReroutingBody': 'Munja beregner en ny cykelrute fra din aktuelle position.',
  'autoRideCheckingDeviationBody': 'Du er væk fra ruten. Munja bekræfter afvigelsen.',
  'autoRideRerouteSuccessBody': 'Den nye rute, ETA og navigation er opdateret.',
  'autoRideRerouteFailedBody': 'Kontrollér internetforbindelsen. Munja prøver igen ved næste vedvarende afvigelse.',
  'autoRideOffRouteBody': 'Du er kørt fra ruten.',
  'autoRideRouteCalculatedBody': 'Cykelruten er beregnet og vises på kortet.',
  'autoRideRouteProgress': 'Ruteprogression',
  'autoRideDestinationNotSaved': 'Destinationen er valgt, men den rigtige cykelrute er endnu ikke gemt.',
  'altitudeShort': 'HØJDE',
  'showFullRoute': 'Vis hele ruten',
  'routeStartedFromWheel': 'Ruten er startet fra hjulet',
  'hourShort': 't',

  // Home + Profile
  'homeBikeLoadFailed': 'Cyklen kunne ikke indlæses.',
  'homeNoActiveBike': 'Ingen aktiv cykel',
  'homeNoActiveBikeBody': 'Opret eller vælg en cykel under Udstyr for at aktivere din Digital Twin.',
  'homeOpenGear': 'Åbn Udstyr',
  'homeOpeningGear': 'ÅBNER UDSTYR',
  'homeActiveChallenge': 'AKTIV UDFORDRING',
  'homeOpponent': 'modstander',
  'homeDaysLeftSingular': 'dag tilbage',
  'homeDaysLeftPlural': 'dage tilbage',
  'profileTitle': 'Profil',
  'profileRiderProfile': 'CYKLISTPROFIL',
  'profileEditProfile': 'REDIGER PROFIL',
  'profileRiderDetails': 'Cyklistoplysninger',
  'profileLanguage': 'SPROG',
  'profileLevelProgress': 'NIVEAUFREMGANG',
  'profileSettingsSection': 'INDSTILLINGER',
  'profileDetails': 'Profiloplysninger',
  'profileFriends': 'Venner',
  'profileRequests': 'Anmodninger',
  'profileFriendChallengeRequests': 'Venne- og udfordringsanmodninger',
  'profileActiveChallenges': 'Aktive udfordringer',
  'profileSeeCurrentBattles': 'Se dine aktuelle dueller',
  'profileAddFriend': 'Tilføj ven',
  'profileChallenge': 'Udfordring',
  'profileChallenges': 'Udfordringer',
  'profileChallengeHub': 'Udfordringscenter',
  'profileFindRiders': 'Find cyklister',
  'profileFindRidersBody': 'Find andre Munja-cyklister, byg dit fællesskab og udfordr hinanden.',
  'profileFindAnotherRider': 'Find en anden Munja-cyklist og byg dit fællesskab.',
  'profileNoFriendsYet': 'Ingen venner endnu',
  'profileViewAll': 'Se alle',
  'profileViewAllFriends': 'Se alle venner',
  'profileNewChallenge': 'Ny udfordring',
  'profileChallengeHubBody': 'Konkurrér med venner, byg fremgang og gør dig klar til Munja Monthly Specials.',
  'profileChallengeInfo': 'Start med 1 mod 1-distance. Flere udfordringstyper, Crystal-belønninger og Monthly Specials er næste udviklingslag.',
  'profileAchievements': 'Præstationer',
  'profileAchievementsCaps': 'PRÆSTATIONER',
  'profileMilestonesBody': 'Milepæle optjent fra din faktiske turhistorik.',
  'profileFirstRide': 'Første tur',
  'profileThreeDayStreak': '3 dages stime',
  'profileComingSoon': 'kommer i næste Munja-step.',
  'profileCreatingRiderId': 'Opretter Rider ID...',
  'profileKm': 'KM',
  'profileStreak': 'STIME',
  'profileRides': 'TURE',
  'profileTotalXp': 'XP I ALT',

  // MUNJA PRO + Challenges
  'proPurchaseFailed': 'MUNJA PRO-købet kunne ikke startes. Prøv igen.',
  'proRestoreFailed': 'MUNJA PRO kunne ikke gendannes. Prøv igen.',
  'proExperience': 'DIN MUNJA-OPLEVELSE',
  'proAdvancedAnalytics': 'Avanceret analyse',
  'proAdvancedAnalyticsDesc': 'Dybere præstationstrends, turindsigter og langsigtet fremgang.',
  'proAiRideAnalysis': 'AI-turanalyse',
  'proAiRideAnalysisDesc': 'Omsæt dine turdata til brugbar feedback og personlige indsigter.',
  'proAiCoach': 'AI-cykelcoach',
  'proAiCoachDesc': 'Personlig coaching baseret på din kørsel, dine mål og din fremgang.',
  'proRoutePlanner': 'Avanceret ruteplanlægger',
  'proRoutePlannerDesc': 'Mere intelligente ruteværktøjer bygget omkring den måde, du cykler på.',
  'proChallenges': 'Pro-udfordringer',
  'proChallengesDesc': 'Særlige udfordringer, dybere mål og udvalgte månedlige events.',
  'proSkinsFrames': 'Eksklusive skins og frames',
  'proSkinsFramesDesc': 'Få adgang til udvalgte Pro-designs, mens Crystals fortsat er en separat økonomi.',
  'proLinkedActive': 'MUNJA PRO er knyttet til din konto og opdateres automatisk.',
  'proLinkedSecure': 'Din MUNJA PRO-status er sikkert knyttet til din Munja-konto.',
  'proYouArePro': 'DU HAR MUNJA PRO',
  'proUnlockMore': 'LÅS MERE AF MUNJA OP',
  'proFeaturesActive': 'Dine Pro-funktioner er aktive på denne konto.',
  'proMoreInsight': 'Mere indsigt. Mere intelligens. Flere måder at udfordre dig selv på.',
  'monthlyCompletedClaimed': 'GENNEMFØRT · BELØNNING HENTET',
  'monthlyCompletedReady': 'GENNEMFØRT · BELØNNING KLAR',
  'expired': 'UDLØBET',
  'monthlyLoading': 'Indlæser Monthly Special...',
  'monthlySpecial': 'MONTHLY SPECIAL',
  'monthlyStartsWithPro': 'Din 30-dages Monthly Special starter automatisk med MUNJA PRO.',
  'monthlyActivatePro': 'Aktivér MUNJA PRO for automatisk at starte denne 30-dages Monthly Special.',
  'monthlyActivating': 'Aktiverer din Monthly Special...',
  'refresh': 'OPDATER',
  'claiming': 'HENTER...',
  'claimReward': 'HENT BELØNNING',
  'activeMembership': 'Aktivt medlemskab',
  'noActiveMembership': 'Intet aktivt medlemskab',
  'monthlySubscription': 'Månedligt abonnement',
  'premiumExperience': 'Premium Munja-oplevelse',
  'freeCaps': 'GRATIS',
  'membershipSync': 'Medlemsstatus synkroniseres automatisk med din Munja-konto.',
  'autoRenewing': 'Månedligt abonnement med automatisk fornyelse. Kan annulleres når som helst via Google Play.',
  'connectingStore': 'FORBINDER TIL GOOGLE PLAY...',
  'getPro': 'FÅ MUNJA PRO',
  'restoring': 'GENDANNER...',
  'restorePurchase': 'GENDAN KØB',
  'challengesTitle': 'Udfordringer',
  'challengeTagline': 'KONKURRÉR · FREMGANG · HISTORIK',
  'readyNextRace': 'Klar til næste duel',
  'completedAppearHistory': 'Gennemførte dueller vises automatisk i din historik.',
  'activeCaps': 'AKTIVE',
  'historyCaps': 'HISTORIK',
  'wins': 'SEJRE',
  'losses': 'NEDERLAG',
  'draws': 'UAFGJORT',
  'winRate': 'SEJRSPROCENT',
  'youCaps': 'DIG',
  'draw': 'UAFGJORT',
  'victory': 'SEJR',
  'defeat': 'NEDERLAG',
  'timeExpired': 'Tiden er udløbet',
  'targetReached': 'Målet er nået',
  'noHistory': 'Ingen udfordringshistorik endnu',
  'historyAppear': 'Gennemførte dueller vises automatisk her.',
  'challengeLoadFailed': 'Udfordringsdata kunne ikke indlæses.',
  'tryAgainCaps': 'PRØV IGEN',
  'ending': 'Slutter',
  'evenNow': 'Det står helt lige lige nu.',
  'distanceDesc': 'Første cyklist til målet vinder.',
  'rideCount': 'Antal ture',
  'rideCountDesc': 'Konkurrér om først at gennemføre et bestemt antal ture.',
  'rideTime': 'Køretid',
  'rideTimeDesc': 'Konkurrér på samlet aktiv køretid.',
  'streakDesc': 'Byg den længste sammenhængende kørestime.',
  'friendsLoadFailed': 'Dine Munja-venner kunne ikke indlæses. Prøv igen.',
  'newChallenge': 'Ny udfordring',
  'challengeType': 'UDFORDRINGSTYPE',
  'chooseRider': 'VÆLG CYKLIST',
  'sending': 'Sender...',
  'sendChallenge': 'Send udfordring',
  'challengeRewardsBalanced': 'Udfordringsbelønninger er balanceret, så Crystals forbliver værdifulde.',
  'challengeARider': 'Udfordr en cyklist',
  'challengeIntro': 'Konkurrér, optjen XP og arbejd mod Munja Crystal-belønninger.',
  'monthlyLoadFailed': 'Monthly Special kunne ikke indlæses.',
  'rewardAlreadyClaimed': 'Denne Monthly Special-belønning er allerede hentet.',
  'completeBeforeClaim': 'Gennemfør Monthly Special, før du henter belønningen.',
  'monthlyNotFound': 'Monthly Special kunne ikke findes.',
  'profileNotFound': 'Din Munja-profil kunne ikke findes.',
  'rewardClaimed': 'Belønning hentet.',
  'rewardClaimFailed': 'Belønningen kunne ikke hentes. Prøv igen.',
  'loading': 'Indlæser...',
  'completed': 'Gennemført',
  'thirtyDays': '30 dage',
  'proCaps': 'PRO',
  'claimed': 'HENTET',
  'claim': 'HENT',
  'monthlyTimerInfo': 'Din 30-dages timer startede, da du aktiverede denne Special. Et nyt kalendermånedsskifte forkorter den ikke.',
  'monthlyActivateInfo': 'Aktivér denne Special, når du er klar. Din personlige 30-dages timer starter først, når du trykker START.',
  'unlockPro': 'LÅS MUNJA PRO OP',
  'rewardClaimedCaps': 'BELØNNING HENTET',
  'specialActive': 'SPECIAL AKTIV',
  'progressCaps': 'FREMGANG',
  'monthlyGoal': 'MÅNEDLIGT MÅL',
  'chooseRiderFirst': 'Vælg en cyklist først',
  'challengeSummary': 'UDFORDRINGSOVERSIGT',
  'goal': 'MÅL',
  'challengeStartsAccept': 'Udfordringen starter, når din ven accepterer invitationen.',
  'loadingFriends': 'Indlæser dine venner...',
  'couldNotCreate': 'Kunne ikke oprette udfordring',
  'tryAgain': 'Prøv igen',
  'noFriendsChallenge': 'Ingen venner at udfordre',
  'addFriendFirst': 'Tilføj først en Munja-ven. Derefter kan du starte en 1 mod 1-udfordring.',
  'requestsLoadFailed': 'Udfordringsanmodninger kunne ikke indlæses. Prøv igen.',
  'acceptFailed': 'Udfordringen kunne ikke accepteres. Prøv igen.',
  'declineFailed': 'Udfordringen kunne ikke afvises. Prøv igen.',
  'declineChallengeQ': 'Afvis udfordring?',
  'cancel': 'Annuller',
  'decline': 'Afvis',
  'cancelFailed': 'Udfordringen kunne ikke annulleres. Prøv igen.',
  'cancelChallengeQ': 'Annuller udfordring?',
  'keepChallenge': 'Behold udfordring',
  'cancelChallenge': 'Annuller udfordring',
  'challengeRequests': 'Udfordringsanmodninger',
  'incoming': 'INDGÅENDE',
  'requestsForYou': 'Anmodninger til dig',
  'outgoing': 'UDGÅENDE',
  'waitingResponse': 'Venter på svar',
  'pending': 'AFVENTER',
  'cancelling': 'Annullerer...',
  'working': 'Arbejder...',
  'accept': 'Acceptér',
  'loadingRequests': 'Indlæser udfordringsanmodninger...',
  'couldNotLoadRequests': 'Kunne ikke indlæse udfordringsanmodninger',

  // Garage / Gear / Digital Twin / Devices / Smart Brake Light
  '3dFileCouldNotOpen': '3D-filen kunne ikke åbnes.',
  '3dModelCouldNotBeSelected': '3D-modellen kunne ikke vælges.',
  'activate': 'Aktivér',
  'activeBike': 'Aktiv cykel',
  'addAnotherProduct': 'Tilføj endnu et produkt',
  'addBike': 'Tilføj cykel',
  'addFirstBikeSync': 'Tilføj din første cykel for at starte synkronisering af din Digital Twin.',
  'addImageCameraGallery': 'Tilføj et billede fra kamera eller galleri.',
  'addProduct': 'Tilføj produkt',
  'appWorksWithoutHardware': 'Munja fungerer også uden hardware.',
  'bandProductSubtitle': 'Fremtidig wearable til turadvarsler og status.',
  'batteryCatalogSubtitle': 'Fremtidigt Munja-batterimodul til forbundet udstyr.',
  'bikeCouldNotActivate': 'Cyklen kunne ikke aktiveres.',
  'bikeCouldNotDelete': 'Cyklen kunne ikke slettes.',
  'bikeCouldNotSave': 'Cyklen kunne ikke gemmes.',
  'bikeCreated': 'Cykel oprettet.',
  'bikeDeleted': 'Cykel slettet.',
  'bikeFirebaseSyncInfo': 'Din cykel synkroniseres med Firebase og din Digital Twin.',
  'bikeInfo': 'Cykelinfo',
  'bikeName': 'Cykelnavn',
  'bikeSavedFileProcessFailed': 'Cyklen blev gemt, men den valgte fil kunne ikke behandles.',
  'bikeUpdated': 'Cykel opdateret.',
  'bikes': 'Cykler',
  'bleUuidMissing': 'BLE-UUID mangler.',
  'brakeLightAlreadyMounted': 'Munja Smart Brake Light er allerede monteret på denne cykel.',
  'brakeLightDashboard': 'Bremselygte-dashboard',
  'brakeLightDashboardSubtitle': 'Live status og styring af din Munja Smart Brake Light.',
  'brakeLightMountedTwin': 'Munja Smart Brake Light er monteret på din Digital Twin.',
  'brakeMountedOnBike': 'Smart Brake Light monteret på cyklen',
  'brakeMountedReady': 'Monteret og klar på din cykel.',
  'brakeProductSubtitle': 'Smart baglygte med automatisk bremselys og Bluetooth.',
  'brakeReady': 'Bremselygte klar',
  'brakingNow': 'Bremser nu',
  'brand': 'Mærke',
  'brightness': 'Lysstyrke',
  'changeImage': 'Skift billede',
  'changeModel': 'Skift model',
  'choose3dModel': 'Vælg 3D-model',
  'chooseFromGallery': 'Vælg fra galleri',
  'chooseGlbGltfModel': 'Vælg en GLB- eller GLTF-model.',
  'chooseImage': 'Vælg billede',
  'chooseMunjaProductForBike': 'Vælg et Munja-produkt til denne cykel.',
  'color': 'Farve',
  'comingSoonCaps': 'KOMMER SNART',
  'confirmDeleteBike': 'Er du sikker på, at du vil slette denne cykel?',
  'connectGear': 'Forbind udstyr',
  'connectedDeviceAppearsHere': 'Din forbundne enhed vises her.',
  'connectedDevices': 'Forbundne enheder',
  'connectedDevicesSubtitle': 'Forbindelser knyttet til denne cykels Digital Twin.',
  'connection': 'Forbindelse',
  'connectionStatus': 'Forbindelsesstatus',
  'connectionStatusSubtitle': 'Bluetooth, Digital Twin og firmware samlet ét sted.',
  'createBike': 'Opret cykel',
  'creating': 'Opretter...',
  'customizeDigitalTwinCaps': 'TILPAS DIGITAL TWIN',
  'delete': 'Slet',
  'deleteBike': 'Slet cykel',
  'detailsAndSetup': 'Detaljer og opsætning',
  'deviceSingular': 'Enhed',
  'devices': 'Enheder',
  'digitalTwin': 'Digital Twin',
  'digitalTwinReady': 'Digital Twin klar',
  'digitalTwinReadyCaps': 'DIGITAL TWIN KLAR',
  'edit': 'Redigér',
  'editBike': 'Redigér cykel',
  'enableDigitalBike3d': 'Aktivér din digitale cykel i 3D.',
  'enterBikeName': 'Indtast et cykelnavn.',
  'farAway': 'Langt væk',
  'firmware': 'Firmware',
  'foundNearbyProducts': 'Munja-produkter fundet i nærheden.',
  'frameSize': 'Stelstørrelse',
  'framesSkinsColors': 'Frames, skins og farver',
  'garage': 'Garage',
  'garageEmpty': 'Din garage er tom.',
  'garageSubtitle': 'Dine cykler, dit udstyr og din Digital Twin samlet ét sted.',
  'glbModelConnected': '3D-model forbundet',
  'gpsCatalogSubtitle': 'Fremtidigt GPS-modul til lokation og tursporing.',
  'hardwareInfo': 'Hardwareinfo',
  'hardwareInfoSubtitle': 'Enhedsstatus, signal og firmwareinformation.',
  'helmet': 'Hjelm',
  'helmetProductSubtitle': 'Fremtidig integration med smart hjelm.',
  'imageCouldNotBeSelected': 'Billedet kunne ikke vælges.',
  'imageSavedFirebase': 'Billedet er gemt og synkroniseret med Firebase.',
  'initializingDigitalTwin': 'Initialiserer Digital Twin...',
  'isConnected': 'er forbundet',
  'kidsBike': 'Børnecykel',
  'lightSettings': 'Lysindstillinger',
  'lightSettingsSubtitle': 'Juster lysstyrke, følsomhed og driftstilstand.',
  'loadingDevices': 'Indlæser enheder...',
  'loadingProducts': 'Indlæser produkter...',
  'loadingYourBikes': 'Indlæser dine cykler...',
  'makeActive': 'Gør aktiv',
  'makeBikeYours': 'Gør cyklen til din',
  'missingUuidCaps': 'UUID MANGLER',
  'mode': 'Tilstand',
  'mountProduct': 'Montér produkt',
  'mountProductFirst': 'Montér først et produkt',
  'mounted': 'Monteret',
  'mountedNoActiveConnections': 'Produkter er monteret, men der blev ikke fundet aktive enhedsforbindelser.',
  'mountedOnBike': 'Monteret på cyklen',
  'mountedOnBikeSubtitle': 'Produkter, der er monteret på din cykel lige nu.',
  'mountedOnDigitalTwin': 'Monteret på Digital Twin',
  'mountedProducts': 'Monterede produkter',
  'mountedProductsSubtitle': 'Munja-produkter monteret på denne cykel.',
  'munjaKeepsStatusTogether': 'Munja samler forbindelse, firmware og Digital Twin-status ét sted.',
  'myBikes': 'Mine cykler',
  'newFrame': 'Ny frame',
  'newImageReadyUpload': 'Nyt billede klar til upload',
  'newLabel': 'NY',
  'no3dModel': 'Ingen 3D-model',
  'noDeviceConnectedYet': 'Ingen enhed forbundet endnu',
  'noModelCaps': 'INGEN MODEL',
  'noMountedProducts': 'Ingen monterede produkter',
  'noProducts': 'Ingen produkter',
  'notEnabled': 'Ikke aktiveret',
  'notInstalled': 'Ikke installeret',
  'notes': 'Noter',
  'off': 'Fra',
  'openCustomizeCaps': 'ÅBN TILPASNING',
  'physicalDeviceConnectsProduct': 'En fysisk enhed forbindes til et konkret Munja-produkt.',
  'physicalDeviceLinked': 'Fysisk enhed knyttet til produkt',
  'product': 'Produkt',
  'productStatus': 'Produktstatus',
  'productStatusSubtitle': 'Forbindelser, firmware og Digital Twin-status.',
  'qrActivationComingSoon': 'QR-aktivering kommer snart.',
  'readyToMount': 'Klar til montering',
  'rear': 'Bagpå',
  'rideSensorCatalogSubtitle': 'Fremtidig ridesensor til kadence, bevægelse og cykeldata.',
  'rssi': 'RSSI',
  'saveChanges': 'Gem ændringer',
  'savedProductsAppearHere': 'Gemte produkter vises her.',
  'scan': 'Scan',
  'scanAgain': 'Scan igen',
  'scanAndMountProducts': 'Scan og montér Munja-produkter på din cykel.',
  'scanBleQrLater': 'Scan via Bluetooth nu. QR-aktivering kommer senere.',
  'scanForProducts': 'Scan efter produkter',
  'scanMountProduct': 'Scan og montér produkt',
  'scanMountProductsTwin': 'Scan og montér Munja-produkter på din Digital Twin.',
  'scanningMunjaProducts': 'Scanner efter Munja-produkter...',
  'sensitivity': 'Følsomhed',
  'showroomDrag360Caps': 'SHOWROOM · TRÆK 360°',
  'signal': 'Signal',
  'skinsQuickTestCaps': 'SKINS · HURTIG TEST',
  'smartBrakeLightCatalogSubtitle': 'Smart baglygte med automatisk bremsedetektering og Bluetooth-forbindelse.',
  'smartBrakeLightDescription': 'Smart baglygte med automatisk bremselys og Bluetooth-forbindelse.',
  'supportsGlbGltf': 'Understøtter GLB og GLTF.',
  'takePhoto': 'Tag billede',
  'tapScanConnect': 'Tryk på et monteret produkt for at scanne og forbinde.',
  'threeDDigitalTwin': '3D Digital Twin',
  'unlockedRewardsCaps': 'OPLÅSTE BELØNNINGER',
  'upToDate': 'Opdateret',
  'update': 'Opdater',
  'uploading': 'Uploader...',
  'useAsPrimaryBike': 'Brug som primær cykel',
  'veryClose': 'Meget tæt på',
  'wheelSize': 'Hjulstørrelse',
  'wrist': 'Håndled',
  'yourDigitalTwin': 'Din Digital Twin',
};
