const Map<String, String> da = {
  'appTitle': 'Munja',

  'welcome': 'Velkommen',
  'welcomeToMunja': 'Velkommen til Munja',
  'howToUseApp': 'Sådan bruger du appen',
  'howToUseAppBody':
      '1. Brug Auto Ride til automatisk tracking.\n2. Brug Mål til mål og vaner.\n3. Brug Udstyr hvis du har en Smart Brake Light.\n4. Åbn din digitale cykel på forsiden.',

  'chooseAvatarMode': 'Vælg din avatar-tilstand',
  'avatarModeSubtitle': 'Gør appen mere personlig før du starter.',
  'setupBeforeStart': 'Opsætning før start',
  'setupBeforeStartSubtitle': 'Tilføj dine oplysninger før du går ind i appen.',
  'name': 'Navn',
  'age': 'Alder',
  'city': 'By',
  'startApp': 'Start app',
  'back': 'Tilbage',
  'next': 'Næste',
  'appMode': 'App-tilstand',

  'home': 'Hjem',
  'ride': 'Tur',
  'challenge': 'Mål',
  'products': 'Udstyr',
  'goals': 'Mål',
  'gear': 'Udstyr',
  'profile': 'Profil',
  'routes': 'Ruter',
  'coach': 'Coach',
  'analytics': 'Analytics',

  'ready': 'Klar',
  'live': 'Live',
  'route': 'Rute',
  'time': 'Tid',
  'level': 'Niveau',
  'distance': 'Distance',
  'speed': 'Hastighed',
  'duration': 'Varighed',
  'avg': 'Gns.',
  'avgSpeed': 'Gns. hastighed',
  'calories': 'Kalorier',
  'routePoints': 'Rutepunkter',
  'total': 'I alt',
  'last': 'Seneste',
  'lastRide': 'Seneste tur',
  'rides': 'Ture',
  'thisWeek': 'Denne uge',
  'weeklyGoal': 'Ugentligt mål',

  'digital_twin_ready': 'Digital tvilling klar',
  'gps': 'GPS',
  'bluetooth': 'Bluetooth',
  'battery': 'Batteri',
  'active': 'Aktiv',
  'inactive': 'Inaktiv',
  'hold_to_start': 'Hold for at starte',
  'hold_to_stop': 'Hold for at stoppe',
  'smart_brake_light_connected': 'Smart Lighting Brake forbundet',
  'tap_bike_to_manage_gear': 'Tryk på cyklen for at administrere udstyr',

  'goodMorning': 'Godmorgen',
  'goodAfternoon': 'God eftermiddag',
  'goodEvening': 'God aften',
  'homeHeadline': 'Din cykel lever digitalt',
  'startAutoRideBody':
      'Hold krystallet for at starte din tur og åbne din digitale cykel.',
  'streak': 'Stime',
  'days': 'dage',

  'greenerTransport': 'Grønnere transport',
  'greenImpact': 'Din grønne effekt',
  'greenImpactSubtitle':
      'Når du vælger cyklen i stedet for bilen, hjælper du med at reducere CO₂ og unødvendige bilture.',
  'co2Saved': 'CO₂ sparet',
  'carKmAvoided': 'Bil-km undgået',
  'greenImpactPositive':
      'Du har allerede gjort en forskel denne uge. Hver tur hjælper med at reducere trafik, brændstofforbrug og CO₂-udledning.',
  'greenImpactStart':
      'Start din første tur og se hvor meget CO₂ du kan spare ved at vælge cyklen i stedet for bilen.',
  'monthlyOverview': 'Månedlig oversigt',
  'monthlyOverviewSubtitle':
      'Se din fremgang måned for måned med distance og grønnere transport.',
  'totalSixMonths': 'I alt 6 måneder',
  'totalCo2Saved': 'CO₂ sparet i alt',

  'hardware': 'Hardware',
  'hardwareNearby': 'Din Smart Brake Light er i nærheden.',
  'noHardwareFound':
      'Ingen hardware fundet lige nu. Appen kan stadig køre alene.',
  'allProducts': 'Alle produkter',
  'smartBrakeLight': 'Smart Brake Light',
  'openStatusSensitivityConnection':
      'Åbn status, følsomhed og forbindelsesinfo',
  'scanSaveManageDevices': 'Scan, gem og administrer dine Munja-enheder',
  'locationPermissionsMissing': 'Lokationstilladelser mangler',
  'bluetoothPermissionMissing': 'Bluetooth eller lokationstilladelse mangler',
  'tryingToConnect': 'Prøver at forbinde…',
  'noSavedDeviceYet': 'Ingen gemt enhed endnu',
  'connected': 'Forbundet',
  'disconnected': 'Afbrudt',
  'couldNotConnect': 'Kunne ikke forbinde',
  'connecting': 'FORBINDER…',
  'notConnected': 'IKKE FORBUNDET',
  'connectNow': 'Forbind nu',
  'brakeLightSensitivity': 'Bremselygte-følsomhed',
  'sensitivityHint':
      'Lav = reagerer hurtigere · Høj = kræver hårdere bremsning',
  'hardwareFound': 'Hardware fundet',
  'softwareOnly': 'Kun software',

  'autoRide': 'Auto Ride',
  'automaticTracking': 'Automatisk tracking',
  'automaticTrackingSubtitle':
      'Knib for at zoome på kortet, og turen stopper automatisk efter 30 sekunder under stopgrænsen.',
  'monitoring': 'Overvågning',
  'notStarted': 'IKKE STARTET',
  'stopMonitoring': 'Stop overvågning',
  'startAutoMode': 'Start auto-tilstand',
  'stopTracking': 'Stop tracking',
  'openAutoRide': 'Åbn Auto Ride',

  'map': 'Kort',
  'mapSubtitle':
      'Brug to fingre til at zoome. Du kan også bruge knapperne eller hoppe tilbage til din nuværende placering.',
  'myLocation': 'Min placering',
  'yourPosition': 'Din position',
  'recentRides': 'Seneste ture',
  'recentRidesSubtitle':
      'Gemte ture beholder deres rute. Tryk på en tur for at se den på kortet.',
  'noRidesSavedYet': 'Ingen ture gemt endnu.',
  'rideRoute': 'Turrute',
  'start': 'Start',
  'finish': 'Slut',

  'bikeChallenge': 'Cykelmål',
  'yourChallenge': 'Dit mål',
  'yourChallengeSubtitle': 'Sæt en deadline og gør cykling til en fast vane.',
  'setChallengeDate': 'Sæt en dato for dit mål.',
  'deadlinePassed': 'Deadline er passeret — sæt en ny 💪',
  'itIsToday': 'Det er i dag! 🚴',
  'daysLeft': 'dage tilbage',
  'setDate': 'Sæt dato',
  'changeDate': 'Skift dato',
  'startChallenge': 'Start mål',
  'planAndGoal': 'Plan og mål',
  'planAndGoalSubtitle':
      'Vælg hvornår du normalt cykler, og justér dit ugentlige mål.',
  'bikeToWork': 'Cykel til arbejde',
  'afterWork': 'Efter arbejde',
  'weekend': 'Weekend',
  'morning': 'Morgen',
  'yourPlan': 'Din plan',
  'openGuide': 'Åbn guide',
  'challengeGuide': 'Målguide',
  'dailySteps': 'Daglige trin',
  'mindset': 'Mindset',
  'startSetGoal': 'Start — sæt dit mål',
  'writeDownDate': 'Skriv en dato ned.',
  'chooseRideTime': 'Vælg hvornår du vil cykle i løbet af ugen.',
  'makeStartEasy': 'Gør starten så nem som muligt.',
  'findRoutineTime': 'Find 10–20 minutter i din rutine.',
  'takeShortRide': 'Sig til dig selv: Jeg tager bare en kort tur i dag.',
  'repeatHabit': 'Gentag det indtil det bliver en vane.',
  'focusProgress': 'Fokusér på fremgang, ikke perfektion.',
  'holdSmallWins': 'Hold fast i de små sejre.',
  'importantAction': 'Det vigtigste er at handle.',

  'profileSettings': 'Avatar & indstillinger',
  'riderIdentity': 'Din cykelidentitet',
  'riderIdentitySubtitle':
      'Vælg en avatar-tilstand og opdater dine oplysninger.',
  'saveAvatarProfile': 'Gem avatar & profil',
  'profileSaved': 'Avatar og profil gemt',

  'myProducts': 'Mit udstyr',
  'nearby': 'I nærheden',
  'scanProductsSubtitle': 'Scan efter Munja-produkter omkring dig.',
  'noProductsNearby': 'Ingen produkter fundet i nærheden.',
  'savedProducts': 'Gemt udstyr',
  'savedProductsSubtitle': 'Enheder du tidligere har gemt.',
  'noSavedProducts': 'Intet gemt udstyr endnu.',
  'saved': 'Gemt',
  'save': 'Gem',
  'add': 'Tilføj',

  'classicRider': 'Klassisk cyklist',
  'speedMode': 'Farttilstand',
  'ecoMode': 'Økotilstand',
  'challengeMode': 'Måltilstand',
  'nightRide': 'Nattur',
  'safeRider': 'Sikker cyklist',

  'smartRoutePlanner': 'Smart ruteplanlægger',
  'smartRouteAi': 'Smart Route AI',
  'searchAddress': 'Søg adresse...',
  'destination': 'Destination',
  'enterWhereYouWantToRide': 'Indtast hvor du vil cykle hen.',
  'generateRoute': 'Generér rute',
  'generating': 'Genererer...',
  'searching': 'Søger...',
  'routePreview': 'Rutevisning',
  'addressSearchNow':
      'Adressesøgning nu. Rigtig road-routing API kommer senere.',
  'whyThisRoute': 'Hvorfor denne rute?',
  'munjaScoresRoute': 'Munja vurderer den ud fra din stil.',
  'safety': 'Sikkerhed',
  'scenic': 'Naturskøn',
  'fitness': 'Fitness',
  'useThisRoute': 'Brug denne rute',
  'generateNewSuggestions': 'Generér nye forslag',
  'routeGenerated': 'Rute genereret',
  'addressNotFound': 'Adresse ikke fundet.',
  'enterAddressFirst': 'Indtast først en adresse.',
  'couldNotFindAddress': 'Kunne ikke finde den adresse.',
  'selectedAndSaved': 'valgt og gemt.',

  'aiRideCoach': 'AI Ride Coach',
  'personalRideIntelligence':
      'Personlig cykelintelligens, restitution og tempo-vejledning.',
  'readiness': 'Klarhed',
  'fatigue': 'Træthed',
  'consistency': 'Konsistens',
  'todayPlan': 'Dagens plan',
  'recommendedRecentHistory': 'Anbefalet baseret på din seneste turhistorik.',
  'rideType': 'Turtype',
  'coachIntelligence': 'Coach-intelligens',
  'whatMunjaNotices': 'Hvad Munja lægger mærke til ved din cykling.',
  'adaptiveRecommendation': 'Adaptiv anbefaling',
  'safetyLayer': 'Sikkerhedslag',
  'performanceTrend': 'Præstationstrend',
  'coachTips': 'Coach-tips',
  'smallActionsBetterRide': 'Små handlinger for en bedre tur.',
  'useRecommendation': 'Brug anbefaling',
  'coachRecommendationActivated': 'Coach-anbefaling aktiveret.',

  'monthlyProgress': 'Månedlig fremgang',
  'lastSixMonthsRiding': 'De sidste 6 måneders cykling.',
  'consistencyCreatesResults': 'Konsistens skaber resultater.',
  'latestSavedTrips': 'Dine seneste gemte ture.',
  'longest': 'Længste',
  'achievements': 'Præstationer',
  'progressUnlocked': 'Fremgang låst op fra denne tur.',
  'yourRidePathWasSaved': 'Din turrute blev gemt.',

  'openMap': 'Åbn kort',
  'stop': 'Stop',
  'aiCoachActivated': 'AI Coach aktiveret',
  'savedToMyProducts': 'gemt i Mit udstyr',
};
