const Map<String, String> en = {
  'appTitle': 'Munja',

  // Login / authentication
  'authGenericError': 'Something went wrong. Please try again.',
  'googleLoginFailed': 'Google sign-in could not be completed.',
  'appleLoginFailed': 'Apple sign-in could not be completed.',
  'enterEmailFirst': 'Enter your email address first.',
  'resetPasswordSent': 'We sent you a password reset link.',
  'resetPasswordFailed': 'The password reset could not be completed.',
  'createMunjaAccount': 'Create your Munja account',
  'welcomeBack': 'Welcome back',
  'createAccountSubtitle':
      'Build your digital bike, connect your products and keep your rides in one place.',
  'loginSubtitle': 'Continue to your bike, your rides and your digital world.',
  'yourName': 'Your name',
  'email': 'Email',
  'emailHint': 'name@email.com',
  'password': 'Password',
  'passwordHint': 'At least 6 characters',
  'forgotPassword': 'Forgot password?',
  'createAccount': 'Create account',
  'signIn': 'Sign in',
  'continueApple': 'Continue with Apple',
  'continueGoogle': 'Continue with Google',
  'alreadyAccount': 'Already have an account?',
  'noAccount': 'Don’t have an account?',
  'or': 'OR',
  'digitalCyclingPlatform': 'DIGITAL CYCLING PLATFORM',
  'rideConnectEvolve': 'RIDE • CONNECT • EVOLVE',
  'language': 'Language',

  'welcome': 'Welcome',
  'welcomeToMunja': 'Welcome to Munja',
  'howToUseApp': 'How to use the app',
  'howToUseAppBody':
      '1. Use Auto Ride for automatic tracking.\n2. Use Goals for goals and habits.\n3. Use Gear if you have a Smart Brake Light.\n4. Open your digital bike on the home screen.',

  'chooseAvatarMode': 'Choose your avatar mode',
  'avatarModeSubtitle': 'Make the app more personal before you start.',
  'setupBeforeStart': 'Set up before start',
  'setupBeforeStartSubtitle': 'Add your details before entering the app.',
  'name': 'Name',
  'age': 'Age',
  'city': 'City',
  'startApp': 'Start app',
  'back': 'Back',
  'next': 'Next',
  'appMode': 'App mode',

  'home': 'Home',
  'ride': 'Ride',
  'challenge': 'Goals',
  'products': 'Gear',
  'goals': 'Goals',
  'gear': 'Gear',
  'profile': 'Profile',
  'routes': 'Routes',
  'coach': 'Coach',
  'analytics': 'Analytics',

  'ready': 'Ready',
  'live': 'Live',
  'route': 'Route',
  'time': 'Time',
  'level': 'Level',
  'distance': 'Distance',
  'speed': 'Speed',
  'duration': 'Duration',
  'avg': 'Avg',
  'avgSpeed': 'Average speed',
  'calories': 'Calories',
  'routePoints': 'Route points',
  'total': 'Total',
  'last': 'Last',
  'lastRide': 'Last ride',
  'rides': 'Rides',
  'thisWeek': 'This week',
  'weeklyGoal': 'Weekly goal',

  'digital_twin_ready': 'Digital Twin Ready',
  'gps': 'GPS',
  'bluetooth': 'Bluetooth',
  'battery': 'Battery',
  'active': 'Active',
  'inactive': 'Inactive',
  'hold_to_start': 'Hold to Start',
  'hold_to_stop': 'Hold to Stop',
  'smart_brake_light_connected': 'Smart Lighting Brake Connected',
  'tap_bike_to_manage_gear': 'Tap Bike to Manage Gear',

  'goodMorning': 'Good morning',
  'goodAfternoon': 'Good afternoon',
  'goodEvening': 'Good evening',
  'homeHeadline': 'Your Bike Lives Digitally',
  'startAutoRideBody':
      'Hold the crystal to start your ride and open your digital bike.',
  'streak': 'Streak',
  'days': 'days',

  'greenerTransport': 'Greener transport',
  'greenImpact': 'Your green impact',
  'greenImpactSubtitle':
      'Choosing the bike instead of the car helps reduce CO₂ and unnecessary car trips.',
  'co2Saved': 'CO₂ saved',
  'carKmAvoided': 'Car km avoided',
  'greenImpactPositive':
      'You have already made a difference this week. Every ride helps reduce traffic, fuel use, and CO₂ emissions.',
  'greenImpactStart':
      'Start your first ride and see how much CO₂ you can save by choosing the bike instead of the car.',
  'monthlyOverview': 'Monthly overview',
  'monthlyOverviewSubtitle':
      'See your progress month by month with distance and greener transport.',
  'totalSixMonths': 'Total 6 months',
  'totalCo2Saved': 'Total CO₂ saved',

  'hardware': 'Hardware',
  'hardwareNearby': 'Your Smart Brake Light is nearby.',
  'noHardwareFound':
      'No hardware found right now. The app can still run on its own.',
  'allProducts': 'All gear',
  'smartBrakeLight': 'Smart Brake Light',
  'openStatusSensitivityConnection':
      'Open status, sensitivity, and connection info',
  'scanSaveManageDevices': 'Scan, save, and manage your Munja devices',
  'locationPermissionsMissing': 'Location permissions missing',
  'bluetoothPermissionMissing': 'Bluetooth or location permission missing',
  'tryingToConnect': 'Trying to connect…',
  'noSavedDeviceYet': 'No saved device yet',
  'connected': 'Connected',
  'disconnected': 'Disconnected',
  'couldNotConnect': 'Could not connect',
  'connecting': 'CONNECTING…',
  'notConnected': 'NOT CONNECTED',
  'connectNow': 'Connect now',
  'brakeLightSensitivity': 'Brake light sensitivity',
  'sensitivityHint': 'Low = reacts faster · High = requires harder braking',
  'hardwareFound': 'Hardware found',
  'softwareOnly': 'Software only',

  'autoRide': 'Auto Ride',
  'automaticTracking': 'Automatic tracking',
  'automaticTrackingSubtitle':
      'Pinch to zoom works on the map, and the ride auto-stops after 30 seconds below the stop threshold.',
  'monitoring': 'Monitoring',
  'notStarted': 'NOT STARTED',
  'stopMonitoring': 'Stop monitoring',
  'startAutoMode': 'Start auto mode',
  'stopTracking': 'Stop tracking',
  'openAutoRide': 'Open Auto Ride',

  'map': 'Map',
  'mapSubtitle':
      'Use two fingers to zoom. You can also use the buttons or jump back to your current location.',
  'myLocation': 'My location',
  'yourPosition': 'Your position',
  'recentRides': 'Recent rides',
  'recentRidesSubtitle':
      'Saved rides keep their route. Tap a ride to see it on the map.',
  'noRidesSavedYet': 'No rides saved yet.',
  'rideRoute': 'Ride route',
  'start': 'Start',
  'finish': 'Finish',

  'bikeChallenge': 'Bike Goals',
  'yourChallenge': 'Your Goal',
  'yourChallengeSubtitle': 'Set a deadline and make cycling a regular habit.',
  'setChallengeDate': 'Set a date for your goal.',
  'deadlinePassed': 'Deadline passed — set a new one 💪',
  'itIsToday': 'It is today! 🚴',
  'daysLeft': 'days left',
  'setDate': 'Set date',
  'changeDate': 'Change date',
  'startChallenge': 'Start goal',
  'planAndGoal': 'Plan and goal',
  'planAndGoalSubtitle':
      'Choose when you usually ride and adjust your weekly goal.',
  'bikeToWork': 'Bike to work',
  'afterWork': 'After work',
  'weekend': 'Weekend',
  'morning': 'Morning',
  'yourPlan': 'Your plan',
  'openGuide': 'Open guide',
  'challengeGuide': 'Goals Guide',
  'dailySteps': 'Daily steps',
  'mindset': 'Mindset',
  'startSetGoal': 'Start — set your goal',
  'writeDownDate': 'Write down a date.',
  'chooseRideTime': 'Choose when you want to ride during the week.',
  'makeStartEasy': 'Make the start as easy as possible.',
  'findRoutineTime': 'Find 10–20 minutes in your routine.',
  'takeShortRide': 'Tell yourself: I will just take a short ride today.',
  'repeatHabit': 'Repeat it until it becomes a habit.',
  'focusProgress': 'Focus on progress, not perfection.',
  'holdSmallWins': 'Hold on to small wins.',
  'importantAction': 'The most important thing is to take action.',

  'profileSettings': 'Avatar & settings',
  'riderIdentity': 'Your rider identity',
  'riderIdentitySubtitle': 'Choose an avatar mode and update your details.',
  'saveAvatarProfile': 'Save avatar & profile',
  'profileSaved': 'Avatar and profile saved',

  'myProducts': 'My Gear',
  'nearby': 'Nearby',
  'scanProductsSubtitle': 'Scan for Munja gear around you.',
  'noProductsNearby': 'No gear found nearby.',
  'savedProducts': 'Saved Gear',
  'savedProductsSubtitle': 'Devices you have saved before.',
  'noSavedProducts': 'No saved gear yet.',
  'saved': 'Saved',
  'save': 'Save',
  'add': 'Add',

  'classicRider': 'Classic Rider',
  'speedMode': 'Speed Mode',
  'ecoMode': 'Eco Mode',
  'challengeMode': 'Goal Mode',
  'nightRide': 'Night Ride',
  'safeRider': 'Safe Rider',

  'smartRoutePlanner': 'Smart Route Planner',
  'smartRouteAi': 'Smart Route AI',
  'searchAddress': 'Search address...',
  'destination': 'Destination',
  'enterWhereYouWantToRide': 'Enter where you want to ride.',
  'generateRoute': 'Generate route',
  'generating': 'Generating...',
  'searching': 'Searching...',
  'routePreview': 'Route preview',
  'addressSearchNow': 'Address search now. Real road-routing API comes later.',
  'whyThisRoute': 'Why this route?',
  'munjaScoresRoute': 'Munja scores it based on your riding style.',
  'safety': 'Safety',
  'scenic': 'Scenic',
  'fitness': 'Fitness',
  'useThisRoute': 'Use this route',
  'generateNewSuggestions': 'Generate new suggestions',
  'routeGenerated': 'Route generated',
  'addressNotFound': 'Address not found.',
  'enterAddressFirst': 'Enter an address first.',
  'couldNotFindAddress': 'Could not find that address.',
  'selectedAndSaved': 'selected and saved.',

  'aiRideCoach': 'AI Ride Coach',
  'personalRideIntelligence':
      'Personal ride intelligence, recovery and pacing guidance.',
  'readiness': 'Readiness',
  'fatigue': 'Fatigue',
  'consistency': 'Consistency',
  'todayPlan': 'Today’s plan',
  'recommendedRecentHistory': 'Recommended based on recent ride history.',
  'rideType': 'Ride type',
  'coachIntelligence': 'Coach intelligence',
  'whatMunjaNotices': 'What Munja notices about your riding.',
  'adaptiveRecommendation': 'Adaptive recommendation',
  'safetyLayer': 'Safety layer',
  'performanceTrend': 'Performance trend',
  'coachTips': 'Coach tips',
  'smallActionsBetterRide': 'Small actions for a better ride.',
  'useRecommendation': 'Use recommendation',
  'coachRecommendationActivated': 'Coach recommendation activated.',

  'monthlyProgress': 'Monthly progress',
  'lastSixMonthsRiding': 'Last 6 months of riding.',
  'consistencyCreatesResults': 'Consistency creates results.',
  'latestSavedTrips': 'Your latest saved rides.',
  'longest': 'Longest',
  'achievements': 'Achievements',
  'progressUnlocked': 'Progress unlocked from this ride.',
  'yourRidePathWasSaved': 'Your ride path was saved.',

  'openMap': 'Open map',
  'stop': 'Stop',
  'aiCoachActivated': 'AI Coach activated',
  'savedToMyProducts': 'saved to My Gear',

  // Bike Customize
  'customize': 'Customize',
  'skins': 'Skins',
  'frame': 'Frame',
  'livePreview': 'Live preview',
  'showroom': 'Showroom',
  'dragToRotateStageSync': 'Drag to rotate · stage sync',
  'frameTrail': 'Trail',
  'frameEnduro': 'Enduro',
  'frameRace': 'Race',
  'frameUrban': 'Urban',
  'colorMidnight': 'Midnight',
  'colorDeepBlack': 'Deep black',
  'colorMunjaMint': 'Munja Mint',
  'colorSignature': 'Signature',
  'colorArctic': 'Arctic',
  'colorCleanWhite': 'Clean white',
  'colorVelocity': 'Velocity',
  'colorElectricBlue': 'Electric blue',
  'colorPulse': 'Pulse',
  'colorPerformanceRed': 'Performance red',
  'colorForest': 'Forest',
  'colorNatureGreen': 'Nature green',
  'skinStandard': 'Standard',
  'skinStandardSubtitle': 'Free colors under Frame',
  'skinBrushedMetal': 'Brushed Metal',
  'skinPremiumMetal': 'Premium metal',
  'skinCarbonFibre': 'Carbon Fibre',
  'skinPremiumCarbon': 'Premium carbon',
  'skinGold': 'Gold',
  'skinPremiumFinish': 'Premium finish',
  'skinIceSilver': 'Ice Silver',
  'skinColdMetallic': 'Cold metallic',
  'skinLavaRed': 'Lava Red',
  'skinPerformanceFinish': 'Performance finish',
  'skinMattBlack': 'Matt Black',
  'skinStealthFinish': 'Stealth finish',
  'skinNeonGreen': 'Neon Green',
  'skinElectricFinish': 'Electric finish',
  'skinTitanium': 'Titanium',
  'skinEliteMetal': 'Elite metal',
  'owned': 'Owned',
  'pro': 'Pro',
  'locked': 'Locked',
  'munjaCrystals': 'Munja Crystals',
  'munjaPro': 'Munja Pro',
  'proExclusive': 'Pro exclusive',
  'crystalSkinDescription':
      'This skin can be unlocked with Munja Crystals. The purchase flow will be connected in the next major step.',
  'proSkinDescription':
      'This skin will be part of Munja Pro. The subscription flow will be connected later.',
  'challengeReward': 'Challenge reward',
  'rewardSkinDescription':
      'This skin is unlocked through a challenge or achievement.',
  'gotIt': 'Got it',
  'comingNext': 'Coming next',
  'freeFrameColorActive':
      'Free frame color active. Premium skin has been disabled.',
  'frameColorSyncFailed': 'The frame color could not be synced. Try again.',
  'frameChangeFailed': 'The frame could not be changed. Try again.',
  'livePremiumPreview': 'Live premium preview',
  'materialPending': 'material pending',
  'activeAndSynced': 'Active and synced',
  'skinActivationFailed': 'The skin could not be activated. Try again.',
  'skinsSectionSubtitle':
      'Premium materials live on your 3D bike · free colors stay under Frame.',
  'livePremiumPreviews': 'Live premium previews',
  'skinStoreComingSoonMessage':
      'The Skin Store catalog is ready. Purchase and unlock will be connected in the next step.',
  'munjaSkinStore': 'Munja Skin Store',
  'premiumProRewardSkins': 'Premium, Pro & reward skins',
  'equipped': 'Equipped',
  'proOnly': 'Pro only',
  'frameSectionSubtitle':
      'Choose geometry and finish without leaving the showroom.',
  'frameFinish': 'Finish',
  'comingSoon': 'Coming soon',

  // Ride Setup / Route Planner
  'rideSetupSearchDestination': 'Search destination',
  'rideSetupCreateRoundTrip': 'Create a round trip',
  'rideSetupGetRouteSuggestions': 'Get route suggestions',
  'rideSetupStartFreeRide': 'Start free ride',
  'rideSetupUseDestination': 'Use destination',
  'rideSetupCreateRoundTripButton': 'Create round trip',
  'rideSetupShowSuggestions': 'Show route suggestions',
  'rideSetupUseSelectedSuggestion': 'Use selected suggestion',
  'rideSetupAddressSuggestionsUnavailable':
      'Address suggestions are unavailable right now.',
  'rideSetupGooglePlacesLocalFallback':
      'Google Places could not be reached – showing local suggestions.',
  'rideSetupShowingLocalSuggestions': 'Showing local suggestions.',
  'rideSetupGpsUnavailable':
      'Munja could not find your GPS position. Check location permission and try again.',
  'rideSetupNoGoodSuggestions': 'Munja found no suitable routes in the area.',
  'rideSetupChooseBestRoute': 'Choose the route that suits you best.',
  'rideSetupSuggestionsLoadFailed': 'Route suggestions could not be loaded.',
  'rideSetupSuggestionsLoadFailedRetry':
      'Route suggestions could not be loaded. Try again.',
  'rideSetupChooseSuggestionFirst': 'Choose a route suggestion first.',
  'rideSetupEnterAndChooseDestination': 'Enter and choose a destination.',
  'rideSetupChooseAddressFromSuggestions':
      'Choose an address from the suggestions.',
  'rideSetupTitle': 'Ride',
  'rideSetupHowRide': 'How do you want to ride?',
  'rideSetupChooseOneOption':
      'Choose one option. Munja only shows the choices you need.',
  'rideSetupHowFar': 'How far?',
  'rideSetupChooseApproxDistance':
      'Choose approximately how long the ride should be.',
  'rideSetupHowRouteFeel': 'How should the route feel?',
  'rideSetupRouteStyleSubtitle': 'Munja adapts the route to your style.',
  'rideSetupFindingSuggestions': 'Finding suggestions...',
  'rideSetupPreparing': 'Preparing...',
  'rideSetupProPlannerActive': 'MUNJA PRO · Advanced Route Planner active',
  'rideSetupProRequired': 'This route type requires MUNJA PRO',
  'rideSetupIntroTitle': 'How do you want to ride today?',
  'rideSetupIntroSubtitle':
      'Choose a ride type. The rest appears only when it is relevant.',
  'rideSetupDestination': 'Destination',
  'rideSetupDestinationSubtitle': 'Choose where you want to go',
  'rideSetupRoundTrip': 'Round trip',
  'rideSetupRoundTripSubtitle': 'Out and back to the same place',
  'rideSetupMunjaSuggestions': 'Munja suggestions',
  'rideSetupMunjaSuggestionsSubtitle': 'Let Munja find the ride',
  'rideSetupFreeRide': 'Free ride',
  'rideSetupFreeRideSubtitle': 'No plan. Just ride.',
  'rideSetupChange': 'CHANGE',
  'rideSetupWhereTo': 'Where do you want to go?',
  'rideSetupSearchAddressOrDestination':
      'Search for an address or destination.',
  'rideSetupFreeHeroTitle': 'No route. Just ride.',
  'rideSetupFreeHeroBody': 'Munja still records your ride, distance and time.',
  'rideSetupChooseRideTypeContinue': 'Choose a ride type to continue',
  'rideSetupWheelReadyFree': 'The wheel is ready for a free ride',
  'rideSetupWheelReadyPlanning': 'The wheel stays ready while you plan',
  'rideSetupSearchAddress': 'Search address',
  'rideSetupBackToStart': 'Back to start',
  'rideSetupSuggestions': 'Suggestions',
  'rideSetupMunjaRecommends': 'Munja recommends',
  'rideSetupNoPlannedRoute': 'No planned route',
  'rideSetupRequiresPro': 'Requires Munja Pro',
  'rideSetupAddressHint': 'Enter address or destination',
  'rideSetupClear': 'Clear',
  'rideSetupLocalTestMode':
      'Test mode: local address suggestions. Add GOOGLE_MAPS_API_KEY for Google suggestions.',
  'rideSetupNoAddresses': 'No addresses found.',
  'rideSetupNoLocalAddresses': 'No local test addresses found.',
  'rideSetupChooseDestination': 'Choose destination',
  'rideSetupEnterAddressRoute': 'Enter an address to find a route.',
  'rideSetupAutomaticRoundTrip': 'Automatic round trip',
  'rideSetupRoundTripInfo':
      'Munja keeps your selected distance and route type.',
  'rideSetupSuggestionsInfo':
      'Munja finds several bicycle routes around you and matches them to your preferred distance.',
  'rideSetupFreeRideInfo': 'Start ride tracking without a fixed destination.',
  'rideSetupAround': 'Around',
  'rideSetupFindNewSuggestions': 'Find new suggestions',
  'rideSetupAnalyzingRoads': 'Munja is analyzing bicycle routes around you...',
  'rideSetupRoute': 'Route',
  'rideSetupVeryCloseDistance': 'Very close to your preferred distance',
  'rideSetupKmFromGoal': 'km from your target',
  'rideSetupBikeRoad': 'Road',
  'rideSetupBikeFamily': 'Family',
  'rideSetupBikeNature': 'Nature',
  'rideSetupBikeQuiet': 'Quiet',
  'rideSetupBikeQuietRoads': 'Quiet roads',
  'rideSetupSelectedRide': 'Your selected ride',

  // Ride Summary + Auto Ride
  'rideSummaryAiAnalysis': 'AI Ride Analysis',
  'rideSummaryAiProSubtitle':
      'Personalized Pro analysis based on this ride and your history.',
  'rideSummaryAiFreeSubtitle':
      'A simple ride recap. MUNJA PRO adds personal history and deeper recommendations.',
  'rideSummaryAnalyzing': 'Analyzing your ride...',
  'rideSummaryAnalysisUnavailable': 'Ride analysis is not available right now.',
  'rideSummaryProAnalysis': 'MUNJA PRO ANALYSIS',
  'rideSummaryRideRecap': 'MUNJA RIDE RECAP',
  'rideSummaryConsistency': 'CONSISTENCY',
  'rideSummaryTrend': 'TREND',
  'rideSummaryFaster': 'FASTER',
  'rideSummaryLonger': 'LONGER',
  'rideSummarySteady': 'STEADY',
  'rideSummaryHeader': 'MUNJA SUMMARY',
  'rideRewards': 'RIDE REWARDS',
  'loadingEarnedRewards': 'Loading earned rewards...',
  'noCrystalRewardRide': 'No Crystal reward was earned for this ride.',
  'rideCompletedReward': 'Ride completed',
  'firstRideBonus': 'First Ride Bonus',
  'totalEarned': 'TOTAL EARNED',
  'crystalRewardsLoadFailed': 'Crystal rewards could not be loaded.',
  'retry': 'RETRY',
  'speedUnitShort': 'km/h',
  'autoRideArrivedSaved': 'You have arrived. The ride will end and be saved.',
  'free': 'FREE',
  'autoRideLoopStarted': 'Round trip started · follow the route',
  'autoRideArrived': 'You have arrived',
  'autoRideConfirmingArrival': 'Confirming arrival...',
  'autoRideRecalculating': 'Recalculating route...',
  'autoRideCheckingRoute': 'Checking route...',
  'autoRideNewRouteReady': 'New route is ready',
  'autoRideCouldNotRecalculate': 'Could not recalculate',
  'autoRideChooseDestinationHome': 'Choose a destination from Home',
  'autoRideRouteActive': 'ROUTE ACTIVE',
  'autoRideThere': 'ARRIVED',
  'autoRideWait': 'WAIT',
  'autoRideOffRoute': 'OFF ROUTE',
  'autoRideUpdated': 'UPDATED',
  'autoRideError': 'ERROR',
  'autoRideNoActiveRoute': 'No active route',
  'autoRideNavigationActive': 'Navigation active',
  'autoRideSpeed': 'SPEED',
  'autoRideRide': 'RIDE',
  'autoRideArrivalBody':
      'Destination reached. The ride will end and be saved automatically.',
  'autoRideConfirmArrivalBody':
      'Stay near the destination while Munja confirms your arrival.',
  'autoRideReroutingBody':
      'Munja is calculating a new bicycle route from your current position.',
  'autoRideCheckingDeviationBody':
      'You are off the route. Munja is confirming the deviation.',
  'autoRideRerouteSuccessBody':
      'The new route, ETA and navigation have been updated.',
  'autoRideRerouteFailedBody':
      'Check your internet connection. Munja will try again after the next persistent deviation.',
  'autoRideOffRouteBody': 'You have left the route.',
  'autoRideRouteCalculatedBody':
      'The bicycle route has been calculated and is shown on the map.',
  'autoRideRouteProgress': 'Route progress',
  'autoRideDestinationNotSaved':
      'The destination is selected, but the bicycle route has not been saved yet.',
  'altitudeShort': 'ALT',
  'showFullRoute': 'Show full route',
  'routeStartedFromWheel': 'The route was started from the wheel',
  'hourShort': 'h',

  // Home + Profile
  'homeBikeLoadFailed': 'The bike could not be loaded.',
  'homeNoActiveBike': 'No active bike',
  'homeNoActiveBikeBody':
      'Create or select a bike in Gear to activate your Digital Twin.',
  'homeOpenGear': 'Open Gear',
  'homeOpeningGear': 'OPENING GEAR',
  'homeActiveChallenge': 'ACTIVE CHALLENGE',
  'homeOpponent': 'opponent',
  'homeDaysLeftSingular': 'day left',
  'homeDaysLeftPlural': 'days left',
  'profileTitle': 'Profile',
  'profileRiderProfile': 'RIDER PROFILE',
  'profileEditProfile': 'EDIT PROFILE',
  'profileRiderDetails': 'Rider details',
  'profileLanguage': 'LANGUAGE',
  'profileLevelProgress': 'LEVEL PROGRESS',
  'profileSettingsSection': 'SETTINGS',
  'profileDetails': 'Profile details',
  'profileFriends': 'Friends',
  'profileRequests': 'Requests',
  'profileFriendChallengeRequests': 'Friend and challenge requests',
  'profileActiveChallenges': 'Active challenges',
  'profileSeeCurrentBattles': 'See your current battles',
  'profileAddFriend': 'Add friend',
  'profileChallenge': 'Challenge',
  'profileChallenges': 'Challenges',
  'profileChallengeHub': 'Challenge Hub',
  'profileFindRiders': 'Find riders',
  'profileFindRidersBody':
      'Find riders, build your crew and challenge each other.',
  'profileFindAnotherRider': 'Find another Munja rider and build your crew.',
  'profileNoFriendsYet': 'No friends yet',
  'profileViewAll': 'View all',
  'profileViewAllFriends': 'View all friends',
  'profileNewChallenge': 'New challenge',
  'profileChallengeHubBody':
      'Compete with friends, build progress and prepare for Munja Monthly Specials.',
  'profileChallengeInfo':
      'Start with 1 vs 1 distance now. More challenge types, Crystal rewards and Monthly Specials are the next progression layer.',
  'profileAchievements': 'Achievements',
  'profileAchievementsCaps': 'ACHIEVEMENTS',
  'profileMilestonesBody': 'Milestones earned from your real ride history.',
  'profileFirstRide': 'First Ride',
  'profileThreeDayStreak': '3 Day Streak',
  'profileComingSoon': 'is coming in the next Munja step.',
  'profileCreatingRiderId': 'Creating Rider ID...',
  'profileKm': 'KM',
  'profileStreak': 'STREAK',
  'profileRides': 'RIDES',
  'profileTotalXp': 'TOTAL XP',

  // MUNJA PRO + Challenges
  'proPurchaseFailed':
      'MUNJA PRO purchase could not be started. Please try again.',
  'proRestoreFailed': 'MUNJA PRO could not be restored. Please try again.',
  'proExperience': 'YOUR MUNJA EXPERIENCE',
  'proAdvancedAnalytics': 'Advanced Analytics',
  'proAdvancedAnalyticsDesc':
      'Deeper performance trends, ride insights and long-term progress.',
  'proAiRideAnalysis': 'AI Ride Analysis',
  'proAiRideAnalysisDesc':
      'Turn your ride data into useful feedback and personal insights.',
  'proAiCoach': 'AI Ride Coach',
  'proAiCoachDesc':
      'Personal coaching based on your riding, goals and progress.',
  'proRoutePlanner': 'Advanced Route Planner',
  'proRoutePlannerDesc':
      'More intelligent route tools built around the way you ride.',
  'proChallenges': 'Pro Challenges',
  'proChallengesDesc':
      'Special challenges, deeper goals and selected monthly events.',
  'proSkinsFrames': 'Exclusive Skins & Frames',
  'proSkinsFramesDesc':
      'Access selected Pro cosmetics while Crystals remain a separate economy.',
  'proLinkedActive':
      'MUNJA PRO is linked to your account and updates automatically.',
  'proLinkedSecure':
      'Your MUNJA PRO status is linked securely to your Munja account.',
  'proYouArePro': 'YOU ARE MUNJA PRO',
  'proUnlockMore': 'UNLOCK MORE OF MUNJA',
  'proFeaturesActive': 'Your Pro features are active on this account.',
  'proMoreInsight':
      'More insight. More intelligence. More ways to challenge yourself.',
  'monthlyCompletedClaimed': 'COMPLETED · REWARD CLAIMED',
  'monthlyCompletedReady': 'COMPLETED · REWARD READY',
  'expired': 'EXPIRED',
  'monthlyLoading': 'Loading Monthly Special...',
  'monthlySpecial': 'MONTHLY SPECIAL',
  'monthlyStartsWithPro':
      'Your 30-day Monthly Special starts automatically with MUNJA PRO.',
  'monthlyActivatePro':
      'Activate MUNJA PRO to automatically start this 30-day Monthly Special.',
  'monthlyActivating': 'Activating your Monthly Special...',
  'refresh': 'REFRESH',
  'claiming': 'CLAIMING...',
  'claimReward': 'CLAIM REWARD',
  'activeMembership': 'Active membership',
  'noActiveMembership': 'No active membership',
  'monthlySubscription': 'Monthly subscription',
  'premiumExperience': 'Premium Munja experience',
  'freeCaps': 'FREE',
  'membershipSync':
      'Membership status is synced automatically with your Munja account.',
  'autoRenewing':
      'Auto-renewing monthly subscription. Cancel anytime through Google Play.',
  'connectingStore': 'CONNECTING TO GOOGLE PLAY...',
  'getPro': 'GET MUNJA PRO',
  'restoring': 'RESTORING...',
  'restorePurchase': 'RESTORE PURCHASE',
  'challengesTitle': 'Challenges',
  'challengeTagline': 'COMPETE · PROGRESS · HISTORY',
  'readyNextRace': 'Ready for the next race',
  'completedAppearHistory': 'Completed races will appear in your history.',
  'activeCaps': 'ACTIVE',
  'historyCaps': 'HISTORY',
  'wins': 'WINS',
  'losses': 'LOSSES',
  'draws': 'DRAWS',
  'winRate': 'WIN RATE',
  'youCaps': 'YOU',
  'draw': 'DRAW',
  'victory': 'VICTORY',
  'defeat': 'DEFEAT',
  'timeExpired': 'Time expired',
  'targetReached': 'Target reached',
  'noHistory': 'No challenge history yet',
  'historyAppear': 'Completed races will appear here automatically.',
  'challengeLoadFailed': 'Challenge data could not be loaded.',
  'tryAgainCaps': 'TRY AGAIN',
  'ending': 'Ending',
  'evenNow': 'It is completely even right now.',
  'distanceDesc': 'First rider to reach the goal.',
  'rideCount': 'Ride Count',
  'rideCountDesc': 'Race to complete a set number of rides.',
  'rideTime': 'Ride Time',
  'rideTimeDesc': 'Compete on total active riding time.',
  'streakDesc': 'Build the longest consistent ride streak.',
  'friendsLoadFailed':
      'Your Munja friends could not be loaded. Please try again.',
  'newChallenge': 'New Challenge',
  'challengeType': 'CHALLENGE TYPE',
  'chooseRider': 'CHOOSE RIDER',
  'sending': 'Sending...',
  'sendChallenge': 'Send Challenge',
  'challengeRewardsBalanced':
      'Challenge rewards are balanced to make Crystals valuable.',
  'challengeARider': 'Challenge a rider',
  'challengeIntro': 'Compete, build XP and work toward Munja Crystal rewards.',
  'monthlyLoadFailed': 'Monthly Special could not be loaded.',
  'rewardAlreadyClaimed':
      'This Monthly Special reward has already been claimed.',
  'completeBeforeClaim':
      'Complete the Monthly Special before claiming the reward.',
  'monthlyNotFound': 'Monthly Special could not be found.',
  'profileNotFound': 'Your Munja profile could not be found.',
  'rewardClaimed': 'Reward claimed.',
  'rewardClaimFailed': 'Reward could not be claimed. Please try again.',
  'loading': 'Loading...',
  'completed': 'Completed',
  'thirtyDays': '30 days',
  'proCaps': 'PRO',
  'claimed': 'CLAIMED',
  'claim': 'CLAIM',
  'monthlyTimerInfo':
      'Your 30-day timer started when you activated this Special. Calendar month changes do not shorten it.',
  'monthlyActivateInfo':
      'Activate this Special whenever you are ready. Your personal 30-day timer starts only when you press START.',
  'unlockPro': 'UNLOCK MUNJA PRO',
  'rewardClaimedCaps': 'REWARD CLAIMED',
  'specialActive': 'SPECIAL ACTIVE',
  'progressCaps': 'PROGRESS',
  'monthlyGoal': 'MONTHLY GOAL',
  'chooseRiderFirst': 'Choose a rider first',
  'challengeSummary': 'CHALLENGE SUMMARY',
  'goal': 'GOAL',
  'challengeStartsAccept':
      'The challenge starts when your friend accepts the invitation.',
  'loadingFriends': 'Loading your friends...',
  'couldNotCreate': 'Could not create challenge',
  'tryAgain': 'Try again',
  'noFriendsChallenge': 'No friends to challenge',
  'addFriendFirst':
      'Add a Munja friend first. Then you can start a 1 vs 1 challenge.',
  'requestsLoadFailed':
      'Challenge requests could not be loaded. Please try again.',
  'acceptFailed': 'Challenge could not be accepted. Please try again.',
  'declineFailed': 'Challenge could not be declined. Please try again.',
  'declineChallengeQ': 'Decline challenge?',
  'cancel': 'Cancel',
  'decline': 'Decline',
  'cancelFailed': 'Challenge could not be cancelled. Please try again.',
  'cancelChallengeQ': 'Cancel challenge?',
  'keepChallenge': 'Keep challenge',
  'cancelChallenge': 'Cancel challenge',
  'challengeRequests': 'Challenge Requests',
  'incoming': 'INCOMING',
  'requestsForYou': 'Requests for you',
  'outgoing': 'OUTGOING',
  'waitingResponse': 'Waiting for response',
  'pending': 'PENDING',
  'cancelling': 'Cancelling...',
  'working': 'Working...',
  'accept': 'Accept',
  'loadingRequests': 'Loading challenge requests...',
  'couldNotLoadRequests': 'Could not load challenge requests',

  // Garage / Gear / Digital Twin / Devices / Smart Brake Light
  '3dFileCouldNotOpen': 'The 3D file could not be opened.',
  '3dModelCouldNotBeSelected': 'The 3D model could not be selected.',
  'activate': 'Activate',
  'activeBike': 'Active bike',
  'addAnotherProduct': 'Add another product',
  'addBike': 'Add bike',
  'addFirstBikeSync': 'Add your first bike to start syncing your Digital Twin.',
  'addImageCameraGallery': 'Add an image from camera or gallery.',
  'addProduct': 'Add product',
  'appWorksWithoutHardware': 'Munja also works without hardware.',
  'bandProductSubtitle': 'Future wearable for ride alerts and status.',
  'batteryCatalogSubtitle': 'Future Munja battery module for connected gear.',
  'bikeCouldNotActivate': 'The bike could not be activated.',
  'bikeCouldNotDelete': 'The bike could not be deleted.',
  'bikeCouldNotSave': 'The bike could not be saved.',
  'bikeCreated': 'Bike created.',
  'bikeDeleted': 'Bike deleted.',
  'bikeFirebaseSyncInfo':
      'Your bike is synced with Firebase and your Digital Twin.',
  'bikeInfo': 'Bike info',
  'bikeName': 'Bike name',
  'bikeSavedFileProcessFailed':
      'The bike was saved, but the selected file could not be processed.',
  'bikeUpdated': 'Bike updated.',
  'bikes': 'Bikes',
  'bleUuidMissing': 'BLE UUID is missing.',
  'brakeLightAlreadyMounted':
      'Munja Smart Brake Light is already mounted on this bike.',
  'brakeLightDashboard': 'Brake Light Dashboard',
  'brakeLightDashboardSubtitle':
      'Live status and controls for your Munja Smart Brake Light.',
  'brakeLightMountedTwin':
      'Munja Smart Brake Light is mounted on your Digital Twin.',
  'brakeMountedOnBike': 'Smart Brake Light mounted on bike',
  'brakeMountedReady': 'Mounted and ready on your bike.',
  'brakeProductSubtitle':
      'Smart rear light with automatic braking and Bluetooth.',
  'brakeReady': 'Brake light ready',
  'brakingNow': 'Braking now',
  'brand': 'Brand',
  'brightness': 'Brightness',
  'changeImage': 'Change image',
  'changeModel': 'Change model',
  'choose3dModel': 'Choose 3D model',
  'chooseFromGallery': 'Choose from gallery',
  'chooseGlbGltfModel': 'Choose a GLB or GLTF model.',
  'chooseImage': 'Choose image',
  'chooseMunjaProductForBike': 'Choose a Munja product for this bike.',
  'color': 'Color',
  'comingSoonCaps': 'COMING SOON',
  'confirmDeleteBike': 'Are you sure you want to delete this bike?',
  'connectGear': 'Connect gear',
  'connectedDeviceAppearsHere': 'Your connected device will appear here.',
  'connectedDevices': 'Connected devices',
  'connectedDevicesSubtitle': 'Connections linked to this bike’s Digital Twin.',
  'connection': 'Connection',
  'connectionStatus': 'Connection status',
  'connectionStatusSubtitle':
      'Bluetooth, Digital Twin and firmware in one place.',
  'createBike': 'Create bike',
  'creating': 'Creating...',
  'customizeDigitalTwinCaps': 'CUSTOMIZE DIGITAL TWIN',
  'delete': 'Delete',
  'deleteBike': 'Delete bike',
  'detailsAndSetup': 'Details and setup',
  'deviceSingular': 'Device',
  'devices': 'Devices',
  'digitalTwin': 'Digital Twin',
  'digitalTwinReady': 'Digital Twin ready',
  'digitalTwinReadyCaps': 'DIGITAL TWIN READY',
  'edit': 'Edit',
  'editBike': 'Edit bike',
  'enableDigitalBike3d': 'Enable your digital bike in 3D.',
  'enterBikeName': 'Enter a bike name.',
  'farAway': 'Far away',
  'firmware': 'Firmware',
  'foundNearbyProducts': 'Munja products found nearby.',
  'frameSize': 'Frame size',
  'framesSkinsColors': 'Frames, skins and colors',
  'garage': 'Garage',
  'garageEmpty': 'Your garage is empty.',
  'garageSubtitle': 'Your bikes, gear and Digital Twin in one place.',
  'glbModelConnected': '3D model connected',
  'gpsCatalogSubtitle': 'Future GPS module for location and ride tracking.',
  'hardwareInfo': 'Hardware info',
  'hardwareInfoSubtitle': 'Device status, signal and firmware information.',
  'helmet': 'Helmet',
  'helmetProductSubtitle': 'Future smart helmet integration.',
  'imageCouldNotBeSelected': 'The image could not be selected.',
  'imageSavedFirebase': 'Image saved and synced with Firebase.',
  'initializingDigitalTwin': 'Initializing Digital Twin...',
  'isConnected': 'is connected',
  'kidsBike': 'Kids bike',
  'lightSettings': 'Light settings',
  'lightSettingsSubtitle': 'Adjust brightness, sensitivity and operating mode.',
  'loadingDevices': 'Loading devices...',
  'loadingProducts': 'Loading products...',
  'loadingYourBikes': 'Loading your bikes...',
  'makeActive': 'Make active',
  'makeBikeYours': 'Make this bike yours',
  'missingUuidCaps': 'MISSING UUID',
  'mode': 'Mode',
  'mountProduct': 'Mount product',
  'mountProductFirst': 'Mount a product first',
  'mounted': 'Mounted',
  'mountedNoActiveConnections':
      'Products are mounted, but no active device connections were found.',
  'mountedOnBike': 'Mounted on bike',
  'mountedOnBikeSubtitle': 'Products currently mounted on your bike.',
  'mountedOnDigitalTwin': 'Mounted on Digital Twin',
  'mountedProducts': 'Mounted products',
  'mountedProductsSubtitle': 'Munja products mounted on this bike.',
  'munjaKeepsStatusTogether':
      'Munja keeps connection, firmware and Digital Twin status together.',
  'myBikes': 'My bikes',
  'newFrame': 'New frame',
  'newImageReadyUpload': 'New image ready to upload',
  'newLabel': 'NEW',
  'no3dModel': 'No 3D model',
  'noDeviceConnectedYet': 'No device connected yet',
  'noModelCaps': 'NO MODEL',
  'noMountedProducts': 'No mounted products',
  'noProducts': 'No products',
  'notEnabled': 'Not enabled',
  'notInstalled': 'Not installed',
  'notes': 'Notes',
  'off': 'Off',
  'openCustomizeCaps': 'OPEN CUSTOMIZE',
  'physicalDeviceConnectsProduct':
      'A physical device connects to a specific Munja product.',
  'physicalDeviceLinked': 'Physical device linked to product',
  'product': 'Product',
  'productStatus': 'Product status',
  'productStatusSubtitle': 'Connections, firmware and Digital Twin status.',
  'qrActivationComingSoon': 'QR activation is coming soon.',
  'readyToMount': 'Ready to mount',
  'rear': 'Rear',
  'rideSensorCatalogSubtitle':
      'Future ride sensor for cadence, motion and bike data.',
  'rssi': 'RSSI',
  'saveChanges': 'Save changes',
  'savedProductsAppearHere': 'Saved products will appear here.',
  'scan': 'Scan',
  'scanAgain': 'Scan again',
  'scanAndMountProducts': 'Scan and mount Munja products on your bike.',
  'scanBleQrLater': 'Scan via Bluetooth now. QR activation comes later.',
  'scanForProducts': 'Scan for products',
  'scanMountProduct': 'Scan and mount product',
  'scanMountProductsTwin':
      'Scan and mount Munja products on your Digital Twin.',
  'scanningMunjaProducts': 'Scanning for Munja products...',
  'sensitivity': 'Sensitivity',
  'showroomDrag360Caps': 'SHOWROOM · DRAG 360°',
  'signal': 'Signal',
  'skinsQuickTestCaps': 'SKINS · QUICK TEST',
  'smartBrakeLightCatalogSubtitle':
      'Smart rear light with automatic brake detection and Bluetooth connection.',
  'smartBrakeLightDescription':
      'Smart rear light with automatic brake light and Bluetooth connection.',
  'supportsGlbGltf': 'Supports GLB and GLTF.',
  'takePhoto': 'Take photo',
  'tapScanConnect': 'Tap a mounted product to scan and connect.',
  'threeDDigitalTwin': '3D Digital Twin',
  'unlockedRewardsCaps': 'UNLOCKED REWARDS',
  'upToDate': 'Up to date',
  'update': 'Update',
  'uploading': 'Uploading...',
  'useAsPrimaryBike': 'Use as primary bike',
  'veryClose': 'Very close',
  'wheelSize': 'Wheel size',
  'wrist': 'Wrist',
  'yourDigitalTwin': 'Your Digital Twin',
};
