const Map<String, String> en = {
  'appTitle': 'Munja',

  'welcome': 'Welcome',
  'welcomeToMunja': 'Welcome to Munja',
  'howToUseApp': 'How to use the app',
  'howToUseAppBody':
      '1. Use Auto Ride for automatic tracking.\n2. Use Goals for goals and habits.\n3. Use Gear if you have a Smart Brake Light.\n4. Open your digital bike on the home screen.',

  'chooseAvatarMode': 'Choose your avatar mode',
  'avatarModeSubtitle': 'Make the app more personal before you start.',
  'setupBeforeStart': 'Set up before start',
  'setupBeforeStartSubtitle': 'Add your details before entering the app.',
  'name': 'Name',
  'age': 'Age',
  'city': 'City',
  'startApp': 'Start app',
  'back': 'Back',
  'next': 'Next',
  'appMode': 'App mode',

  'home': 'Home',
  'ride': 'Ride',
  'challenge': 'Goals',
  'products': 'Gear',
  'goals': 'Goals',
  'gear': 'Gear',
  'profile': 'Profile',
  'routes': 'Routes',
  'coach': 'Coach',
  'analytics': 'Analytics',

  'ready': 'Ready',
  'live': 'Live',
  'route': 'Route',
  'time': 'Time',
  'level': 'Level',
  'distance': 'Distance',
  'speed': 'Speed',
  'duration': 'Duration',
  'avg': 'Avg',
  'avgSpeed': 'Average speed',
  'calories': 'Calories',
  'routePoints': 'Route points',
  'total': 'Total',
  'last': 'Last',
  'lastRide': 'Last ride',
  'rides': 'Rides',
  'thisWeek': 'This week',
  'weeklyGoal': 'Weekly goal',

  'digital_twin_ready': 'Digital Twin Ready',
  'gps': 'GPS',
  'bluetooth': 'Bluetooth',
  'battery': 'Battery',
  'active': 'Active',
  'inactive': 'Inactive',
  'hold_to_start': 'Hold to Start',
  'hold_to_stop': 'Hold to Stop',
  'smart_brake_light_connected': 'Smart Lighting Brake Connected',
  'tap_bike_to_manage_gear': 'Tap Bike to Manage Gear',

  'goodMorning': 'Good morning',
  'goodAfternoon': 'Good afternoon',
  'goodEvening': 'Good evening',
  'homeHeadline': 'Your Bike Lives Digitally',
  'startAutoRideBody':
      'Hold the crystal to start your ride and open your digital bike.',
  'streak': 'Streak',
  'days': 'days',

  'greenerTransport': 'Greener transport',
  'greenImpact': 'Your green impact',
  'greenImpactSubtitle':
      'Choosing the bike instead of the car helps reduce CO₂ and unnecessary car trips.',
  'co2Saved': 'CO₂ saved',
  'carKmAvoided': 'Car km avoided',
  'greenImpactPositive':
      'You have already made a difference this week. Every ride helps reduce traffic, fuel use, and CO₂ emissions.',
  'greenImpactStart':
      'Start your first ride and see how much CO₂ you can save by choosing the bike instead of the car.',
  'monthlyOverview': 'Monthly overview',
  'monthlyOverviewSubtitle':
      'See your progress month by month with distance and greener transport.',
  'totalSixMonths': 'Total 6 months',
  'totalCo2Saved': 'Total CO₂ saved',

  'hardware': 'Hardware',
  'hardwareNearby': 'Your Smart Brake Light is nearby.',
  'noHardwareFound':
      'No hardware found right now. The app can still run on its own.',
  'allProducts': 'All gear',
  'smartBrakeLight': 'Smart Brake Light',
  'openStatusSensitivityConnection':
      'Open status, sensitivity, and connection info',
  'scanSaveManageDevices': 'Scan, save, and manage your Munja devices',
  'locationPermissionsMissing': 'Location permissions missing',
  'bluetoothPermissionMissing': 'Bluetooth or location permission missing',
  'tryingToConnect': 'Trying to connect…',
  'noSavedDeviceYet': 'No saved device yet',
  'connected': 'Connected',
  'disconnected': 'Disconnected',
  'couldNotConnect': 'Could not connect',
  'connecting': 'CONNECTING…',
  'notConnected': 'NOT CONNECTED',
  'connectNow': 'Connect now',
  'brakeLightSensitivity': 'Brake light sensitivity',
  'sensitivityHint': 'Low = reacts faster · High = requires harder braking',
  'hardwareFound': 'Hardware found',
  'softwareOnly': 'Software only',

  'autoRide': 'Auto Ride',
  'automaticTracking': 'Automatic tracking',
  'automaticTrackingSubtitle':
      'Pinch to zoom works on the map, and the ride auto-stops after 30 seconds below the stop threshold.',
  'monitoring': 'Monitoring',
  'notStarted': 'NOT STARTED',
  'stopMonitoring': 'Stop monitoring',
  'startAutoMode': 'Start auto mode',
  'stopTracking': 'Stop tracking',
  'openAutoRide': 'Open Auto Ride',

  'map': 'Map',
  'mapSubtitle':
      'Use two fingers to zoom. You can also use the buttons or jump back to your current location.',
  'myLocation': 'My location',
  'yourPosition': 'Your position',
  'recentRides': 'Recent rides',
  'recentRidesSubtitle':
      'Saved rides keep their route. Tap a ride to see it on the map.',
  'noRidesSavedYet': 'No rides saved yet.',
  'rideRoute': 'Ride route',
  'start': 'Start',
  'finish': 'Finish',

  'bikeChallenge': 'Bike Goals',
  'yourChallenge': 'Your Goal',
  'yourChallengeSubtitle': 'Set a deadline and make cycling a regular habit.',
  'setChallengeDate': 'Set a date for your goal.',
  'deadlinePassed': 'Deadline passed — set a new one 💪',
  'itIsToday': 'It is today! 🚴',
  'daysLeft': 'days left',
  'setDate': 'Set date',
  'changeDate': 'Change date',
  'startChallenge': 'Start goal',
  'planAndGoal': 'Plan and goal',
  'planAndGoalSubtitle':
      'Choose when you usually ride and adjust your weekly goal.',
  'bikeToWork': 'Bike to work',
  'afterWork': 'After work',
  'weekend': 'Weekend',
  'morning': 'Morning',
  'yourPlan': 'Your plan',
  'openGuide': 'Open guide',
  'challengeGuide': 'Goals Guide',
  'dailySteps': 'Daily steps',
  'mindset': 'Mindset',
  'startSetGoal': 'Start — set your goal',
  'writeDownDate': 'Write down a date.',
  'chooseRideTime': 'Choose when you want to ride during the week.',
  'makeStartEasy': 'Make the start as easy as possible.',
  'findRoutineTime': 'Find 10–20 minutes in your routine.',
  'takeShortRide': 'Tell yourself: I will just take a short ride today.',
  'repeatHabit': 'Repeat it until it becomes a habit.',
  'focusProgress': 'Focus on progress, not perfection.',
  'holdSmallWins': 'Hold on to small wins.',
  'importantAction': 'The most important thing is to take action.',

  'profileSettings': 'Avatar & settings',
  'riderIdentity': 'Your rider identity',
  'riderIdentitySubtitle': 'Choose an avatar mode and update your details.',
  'saveAvatarProfile': 'Save avatar & profile',
  'profileSaved': 'Avatar and profile saved',

  'myProducts': 'My Gear',
  'nearby': 'Nearby',
  'scanProductsSubtitle': 'Scan for Munja gear around you.',
  'noProductsNearby': 'No gear found nearby.',
  'savedProducts': 'Saved Gear',
  'savedProductsSubtitle': 'Devices you have saved before.',
  'noSavedProducts': 'No saved gear yet.',
  'saved': 'Saved',
  'save': 'Save',
  'add': 'Add',

  'classicRider': 'Classic Rider',
  'speedMode': 'Speed Mode',
  'ecoMode': 'Eco Mode',
  'challengeMode': 'Goal Mode',
  'nightRide': 'Night Ride',
  'safeRider': 'Safe Rider',

  'smartRoutePlanner': 'Smart Route Planner',
  'smartRouteAi': 'Smart Route AI',
  'searchAddress': 'Search address...',
  'destination': 'Destination',
  'enterWhereYouWantToRide': 'Enter where you want to ride.',
  'generateRoute': 'Generate route',
  'generating': 'Generating...',
  'searching': 'Searching...',
  'routePreview': 'Route preview',
  'addressSearchNow': 'Address search now. Real road-routing API comes later.',
  'whyThisRoute': 'Why this route?',
  'munjaScoresRoute': 'Munja scores it based on your riding style.',
  'safety': 'Safety',
  'scenic': 'Scenic',
  'fitness': 'Fitness',
  'useThisRoute': 'Use this route',
  'generateNewSuggestions': 'Generate new suggestions',
  'routeGenerated': 'Route generated',
  'addressNotFound': 'Address not found.',
  'enterAddressFirst': 'Enter an address first.',
  'couldNotFindAddress': 'Could not find that address.',
  'selectedAndSaved': 'selected and saved.',

  'aiRideCoach': 'AI Ride Coach',
  'personalRideIntelligence':
      'Personal ride intelligence, recovery and pacing guidance.',
  'readiness': 'Readiness',
  'fatigue': 'Fatigue',
  'consistency': 'Consistency',
  'todayPlan': 'Today’s plan',
  'recommendedRecentHistory': 'Recommended based on recent ride history.',
  'rideType': 'Ride type',
  'coachIntelligence': 'Coach intelligence',
  'whatMunjaNotices': 'What Munja notices about your riding.',
  'adaptiveRecommendation': 'Adaptive recommendation',
  'safetyLayer': 'Safety layer',
  'performanceTrend': 'Performance trend',
  'coachTips': 'Coach tips',
  'smallActionsBetterRide': 'Small actions for a better ride.',
  'useRecommendation': 'Use recommendation',
  'coachRecommendationActivated': 'Coach recommendation activated.',

  'monthlyProgress': 'Monthly progress',
  'lastSixMonthsRiding': 'Last 6 months of riding.',
  'consistencyCreatesResults': 'Consistency creates results.',
  'latestSavedTrips': 'Your latest saved rides.',
  'longest': 'Longest',
  'achievements': 'Achievements',
  'progressUnlocked': 'Progress unlocked from this ride.',
  'yourRidePathWasSaved': 'Your ride path was saved.',

  'openMap': 'Open map',
  'stop': 'Stop',
  'aiCoachActivated': 'AI Coach activated',
  'savedToMyProducts': 'saved to My Gear',
};
